### ISSUE TITLE
Support rTorrent for MA3 and JMM Desktop

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmclient#10]
Support rTorrent for MA3 and JMM Desktop

bradley.bristowstagg

Definitely a good option.  I'm currently looking at moving my torrents off my MediaPortal and onto my NAS (running FreeNAS 8.2) and rTorrent is the only option there.

**Comment by ElementalCrisis** [comment]
@bigretromike has submitted a PR #270 that should make any torrent program work with JMM Desktop by specifying where your torrent file are downloaded.

**Comment by CatmanIX** [comment]
@ElementalCrisis having integrated support for rTorrent like is currently in place for uTorrent would be more preferable though. rTorrent is probably the most popular with people who have dedicated media servers and such so it would probably be worth it to impliment.

**Comment by ElementalCrisis** [comment]
I agree, it would be nice but its something that would take some time to add. Plus support for the other top programs would have to be added which is why for now, the torrent black hole feature is the way to go.

**Comment by bigretromike** [comment]
rTorrent is support thru Black Hole concept. rTorrent can have input folder, and black hole is solution for this. Usually rtorrent works as headless daemon and it can scan one folder without problem. and if its remote host then mouting remote folder on your local machine should be problem ;-)

**Comment by ElementalCrisis** [comment]
The only alternative I can think of that would be beneficial for more than single client would be magnet support in JMM Desktop. As it stands adding support for additional torrent programs is a low priority thanks to the solution provided by @bigretromike, that's not to say they won't ever get added but what will most likely happen is someone who wants it will most likely add it.
