### ISSUE TITLE
Error message: "Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by SuperFlue** [japanesemediamanager/jmmclient#101]
Here i am with another issue.

The desktop client pops up with this error message constantly:
"Object reference not set to an instance of an object"

JMM server is hosted on another computer than the one running JMM desktop. On the machine hosting JMM server I can run the desktop client without error.

Error message in the log:
```
[2014-11-17 17:11:09:353] Error|MainWindow.DisplayMainTab => JMMServerVM.RefreshAllCustomTags => Utils.ShowErrorMessage System.NullReferenceException: Object reference not set to an instance of an object.
   at JMMClient.JMMServerVM.RefreshAllCustomTags() in c:\Projects\GitHub\jmmclient\JMMClient\ViewModel\JMMServerVM.cs:line 2062
```

**Comment by jmediamanager** [comment]
@SuperFlue could you please let me know what database you are using?

As you said, it sounds like it has failed to create the basic custom tag info

**Comment by jmediamanager** [comment]
I have made a change so that when JMM Server restarts, it re-creates the Custom Tags if there are none existing in the database

Available in 3.4.2.10

**Comment by bond4u** [comment]
Upgraded to 3.4.3.2 and this error pops up when going to Utilities > Multiple Files > Refresh

**Comment by jmediamanager** [comment]
@bond4u Could you raise this as a separate issue and post the error from the logs if you can see it.
