### ISSUE TITLE
[Error] Not using MAL link as this MAL ID (some numbers) is already in use by "other numbers"

### ISSUE THREAD

**Issue by Darken5** [japanesemediamanager/jmmclient#104]
I've been trying to go through my anime and link them to MAL, and im getting his error for some of the series.

Amaenaide yo!!, Amaenaide yo!! Katsu!!, Ao No Exorcist, and Ao No Exorcist Gekijouban... so far.

Error's by series:
Amaenaide yo!!: Not using MAL link as this MAL ID (591) is already in use by 3168
Amaenaide yo!! Katsu!!: Not using MAL link as this MAL ID (886) is already in use by 4145
Ao No Exorcist: Not using MAL link as this MAL ID (9919) is already in use by 8148
Ao No Exorcist Gekijouban: Not using MAL link as this MAL ID (11737) is already in use by 8689

There all linked fine to "The TvDB" (tried unlinking one from TvDB and linking to MAL, didn't work)

EDIT: just checked the anidb link for Amaenaide yo!! and it went to "http://anidb.net/perl-bin/animedb.pl?show=anime&aid=3168" which is Amaenaide yo!! So the anidb link is right

EDIT 2: the other 3 link to AniDB correct too.

**Comment by jmediamanager** [comment]
Both Issues will be fixed i  Release 3.4.2.14

- Allow MAL links to be re-assigned without needing to delete first
- Rendering issues when TvDB or Trakt links are added or removed
