### ISSUE TITLE
[Enhancement] Ability to link multiple MAL links to 1 AniDB Series

### ISSUE THREAD

**Issue by Darken5** [japanesemediamanager/jmmclient#106]
This is not something that comes up often. But I just got a hold of "Scryed Alteration I: Tao" and "Scryed Alteration II: Quan". AniDB considers them 1 series. MAL considers them seperate.

AniDB link: http://anidb.net/perl-bin/animedb.pl?show=anime&aid=8342

MAL Links:
Scryed Alteration I: Tao  :  http://myanimelist.net/anime/10592/Scryed_Alteration_I:_Tao
Scryed Alteration II: Quan  :  http://myanimelist.net/anime/12223/Scryed_Alteration_II:_Quan

Honestly, the way JMM treats MAL linking is probable the best way as to avoid too many f-ups when auto linking, or even manually linking. But an "Multi-Link"/"Advanced" button on the MAL linking popup that will change it to resemble  the Trakt/TvDB linking popups and allow you to select the relation to the AniDB ep would be efficient, tidy, and user friendly. 

Not an immediate issue as I don't think this issue happens often.

**Comment by CatmanIX** [comment]
You mean like [this](http://i.imgur.com/qlBYBgo.png)? JMM has always been able to do that.

**Comment by Darken5** [comment]
i try adding a mal link and this is the error i get.
![mal error](https://cloud.githubusercontent.com/assets/9792820/5958138/a56625fc-a78f-11e4-8bf6-e61fb2f1df64.png)

**Comment by Darken5** [comment]
and if i select "Starting Episode # 1" it just overwrites "Scryed Alteration I: Tao"

**Comment by jmediamanager** [comment]
Ok looks like this is a MySQL/SQLite bug, as it works fine for me on SQL Server.
Hopefully I will get a fix out today

**Comment by jmediamanager** [comment]
Available in 3.4.2.15
