### ISSUE TITLE
JMM Desktop not answering

### ISSUE THREAD

**Issue by Blackdixxa** [japanesemediamanager/jmmclient#108]
Hi,

I have an issue with JMM Desktop since a few months, whenever I try to access the dashbord or collection tab the program is not answering anymore
I was on last stable and thought maybe if I reinstall everything I would correct the problem but no.
I'm currently on lastest beta : 3.4.2.8.
![jmm_bug](https://cloud.githubusercontent.com/assets/10331553/5564296/10c6fdf0-8eb6-11e4-97e8-ecd8e8fdf9b9.png)
here an extract from last  log :

[2014-12-28 17:30:32:259] Trace|BackgroundWorker.WorkerThreadStart => MainWindow.showDashboardWorker_DoWork => DashboardVM.RefreshData Dashboard Time: RefreshGroupsSeriesData: 395,4956
[2014-12-28 17:30:36:883] Warn|UTorrentHelperVM.Init => UTorrentHelper.Init => UTorrentHelper.PopulateToken Credentials are not valid for uTorrent
[2014-12-28 17:31:42:667] Trace|BackgroundWorker.WorkerThreadStart => MainWindow.showDashboardWorker_DoWork => DashboardVM.RefreshData Dashboard Time: RefreshGroupsSeriesData: 201,2511
[2014-12-28 17:31:45:991] Trace|EventRoute.InvokeHandlersImpl => DashboardControl.btnExpandDashWatchNext_Click => DashboardVM.RefreshEpsWatchNext_Recent Dashboard Time: RefreshEpsWatchNext_Recent: contracts: 817.4423

On JMM Server side everything seems to run fine it's hashing new episode as they are added etc.

I've deleted everything and reinstalled both Desktop and Server and they are on MySQL. One odd thing I noticed on full reinstallation, all the settings were there again. Where are stored JMM settings and config files ?

server log as requested on IRC: 
https://drive.google.com/file/d/0BwTB3YKZ53RibzRzT2FHUWVLeW8/view?usp=sharing

**Comment by jmediamanager** [comment]
The settings are stored in the config file, import folders are stored in the database

**Comment by jmediamanager** [comment]
For reference this was partially solved by getting JMM Desktop to use the same images folder as JMM Server.
I believe the problem is related to images being missing.

This solved the issue on the Metro dashboard.
But the 'Continue Watching' widget is still slow on the regular dashboard.
 The regular widget is probably trying to use the image without checking that it exists first.

**Comment by Blackdixxa** [comment]
any idea on how to correct this ?
should I erase all my images and redownload them or maybe we should have a button to force download of images.

**Comment by jmediamanager** [comment]
It should re-download the images ever time you start JMM server.
I probably need to add some logging to see where it is going wrong

**Comment by Blackdixxa** [comment]
I have at least 1 or 2 animes names if it can help.
Whenever I try to enter the anime tab to check episode or stuff like that it takes ages to open.

**Comment by jmediamanager** [comment]
yup, I'll need to put some logging in the image download code first, to see why it is not downloading it.

But also need to change the code so it can properly handle missing images

**Comment by jmediamanager** [comment]
Ok I figured out why it was so slow for you @Blackdixxa 

You must definitely be missing some images.
On the normal continue watching widget, if it can't find the image locally, it tries to directly use the TvDB URL as the image source.
For the last few days the TvDB image server has been extremely slow.
This resulted in your widget rendering slowly as well.

On the Metro dashboard, if the image is missing it just displays a blank space instead.

My intention is to remove the functionality which displays it directly from the website.
This way at least you will know that the image is missing, and you can rectify the problem locally
