### ISSUE TITLE
quick search for reviews/comparisons

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/jmmclient#112]
i think it would be great to have a quick search for reviews of fansubbing groups, episodes and series as a hole.

we should have options for searching for all 3 categories at once or a combination of them.

also if no entry is found for series and such then you could ask the user to make a entry with screenshots atleast. 

ofc this is only a ease of use thing and should not have a high prio unless you really want something like this. (ofc there is alot more sites that do reviews (that we should get a good list on, but i feel cry is important as he looks at a per episode basis across groups and judges them hard with screens)) 

http://www.crymore.net/
http://compare.bakashots.me/
http://fansub.co/

**Comment by jmediamanager** [comment]
Yeah the AniDB API doesn't support this unfortunately.

Getting reviews from other sites would also take a quite a bit of work, linking etc as well

**Comment by AreFinstad** [comment]
you could use keyword searches tho, just have a window where all the hits are displayed and let the user open them. you could i guess also filter per site and so on after the keywords.

think this can be done with just Google TBH. ofc its not error free as it will give hits from everything about the title (which is a good thing). obv with that in mind we could add tags to the searches aswell.

**Comment by AreFinstad** [comment]
ofc such quick auto searches can be done with the Shanaproject site aswell if you think something like that is needed.

we could collaborate (the community as a hole) to find all the most used sites and log all the tags they use for their posts and such to refine the searches.
