### ISSUE TITLE
Poster previews appear blank, even while a legitimate file exists.

### ISSUE THREAD

**Issue by MasterWormy** [japanesemediamanager/jmmclient#117]
![jmmdposterissue](https://cloud.githubusercontent.com/assets/10624542/5830442/94906bfa-a174-11e4-8724-7b7e8dc2115a.jpg)

This only affects posters sourced from MovieDB, and only some of those. I can't notice any other obvious patterns.

Description:
In the Images tab of a series in JMMDesktop, preview images of posters will appear blank (white). Clicking the magnifying glass below the blank pictures, however will open a file with Windows Photo Viewer (or default image program).

I should mention that using the image manager menu in the MyAnime3 plugin for MediaPortal displays everything correctly. (But being MP, it's kinda slow and annoying to use as a permanent alternative). 

Tried to provide logs by removing Akira from my DB, and relinking to MovieDB, viewing images. Not sure how useful this will be.

Desktop Log - https://www.dropbox.com/s/ctkhj6nc9kljn1n/JMMDesktopLog%202015-01-19%20%28bug1%29.txt?dl=0

Server Log - https://www.dropbox.com/s/ucq2q6zjn2jen0o/JMMServerLog%202015-01-19%20%28bug1%29.txt?dl=0

**Comment by jmediamanager** [comment]
Ok I just noticed this on my system for one image from TvDB.
No errors in the logs, but when debugging I can see that the WPF Image control thinks it is an invalid image, but I have no issues opening it with the default image viewer

For my Testing Reference
Absolute Duo
.\Images\TvDB\seasons\283963-1.jpg

I will also try the movie you have mentioned.

I suspect something went wrong with the downloading process.

**Comment by jmediamanager** [comment]
Yeah Laputa worked for me fine.
You might try locating those files, deleting them and pressing the 'Update Info' button for the movie

**Comment by MasterWormy** [comment]
I was just thinking that. So I cleared all my JMM image directories, there are still blank poster entries, but now the magnifying glass doesn't connect to any files (Error. The system cannot find the file specified). 
Is there some way to remove these old entries that no longer exist?

**Comment by jmediamanager** [comment]
Yeah if you click on the "Run Import" button in JMM Server, one of the things it will do is check iff all your images actually exist, and then  download any missing ones

**Comment by MasterWormy** [comment]
Ok, my database got corrupted and was killing my PC after I deleted the image folders and it automatically queued new image aquisitions. I also hit run import while this was going on and the action queue became corrupt, so I eventually managed to delete my entire db and start anew.

(Sticking with Laputa as example) I can confirm that even after having completely rebuilt my jmmdb, and pressing run import, there are blank preview images which do not link to existing files, and there is no way I can get rid of them from JMMDesktop. Run Import does not do it for me.

Will do more testing and provide logs tomorrow.

**Comment by jmediamanager** [comment]
Ok let me know

**Comment by MasterWormy** [comment]
Well, that has sort of sorted itsself out now. With enough 'Update Info' clicks on the various image sources, all the blank posters and fanarts are properly downloaded onto my system.

Some related oddities do persist however:
1) It takes a few Updates to get a completely downloaded selection of posters etc.
2) I have set MovieDB Poster downloads limit to 8, and yet with a lot of my anime I have a lot more than that. For eg. I have 31 posters from MovieDB available for Laputa.
3) I think it's fair to say that JMM's image handling could be more robust. A proper way to refresh the Image folder & database would probably have prevented my problems. It could also check and enforce the limits set in the program.
But this is understandably not high priority.

Happy to call it a day on this one.

**Comment by jmediamanager** [comment]
1 - Just remember that it queues all the image download commands. Was your queue empty before you pressed the update button again?
2 - I will test this again, but it worked for me when I tested Laputa
3 - The Run Import button is supposed to do that, so I will leave this issue open so I can investigate

**Comment by jmediamanager** [comment]
2 - Just reviewed the code, 2 separate bugs

a - It is using the poster amount for both fanarts and posters
b - Each time you update the movie info, it downloads extra images, rather than looking at what it has already downloaded

**Comment by MasterWormy** [comment]
1 - Yes, as far as what Desktop was showing about the server queue, I would wait for the queue to be empty before checking the Images tab and then Updating Info again. Still had to do it 2-3 times for some Anime.

Glad you actually found something legit and it's not just me wasting your time.

**Comment by ElementalCrisis** [comment]
I believe the first issue was fixed awhile ago and the blank image issue has been fixed and will be available in 3.6.0.1.

https://github.com/japanesemediamanager/jmmserver/pull/278
