### ISSUE TITLE
Some movies refuse to link to MovieDB.

### ISSUE THREAD

**Issue by MasterWormy** [japanesemediamanager/jmmclient#118]
Specifically,
King of Thorn
![bug2_kot](https://cloud.githubusercontent.com/assets/10624542/5830750/40b7111e-a179-11e4-841f-2390b8a61109.jpg)

and
Time of Eve: The Movie
![bug2_toe](https://cloud.githubusercontent.com/assets/10624542/5830717/c55c061e-a178-11e4-9882-77fe4c929ad8.jpg)

I have tried manually linking these movies to the Community Recommendation and the movie links directly (both are correct in web browser), but no change is made after clicking 'Use This'.
These are the only two movies with this issue on my system.

Desktop Log - https://www.dropbox.com/s/8prkrft7rfyv9nm/JMMDesktopLog%202015-01-19%20%28bug2%29.txt?dl=0

Server Log - https://www.dropbox.com/s/2iq5d6c7frl8sgh/JMMServerLog%202015-01-19%20%28bug2%29.txt?dl=0

**Comment by jmediamanager** [comment]
@MasterWormy  I think I fixed this error in the latest release

You you please try updating to 3.4.2.11, and then taking another look please

**Comment by MasterWormy** [comment]
Yep, confirmed fixed in 3.4.2.11
