### ISSUE TITLE
smarter group collecting. 

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/jmmclient#120]
we should have a way to easier manage series with multiple fansubbing groups, not just deleting files from the same episode.
JMM should inform us if you have a release of another group than the other episodes,
say if you collect a series from FFF or something and you have a few episodes from HorribleSubs or something that have entered your collecting without the user noticing.
if there is only one file per episode you wont know about the error and difference between subbing groups unless you check the series page per series, this can work into the fangroup ranking/tagging we already have an issue on aswell.

for an example, you are the first 6 episodes of a series from one group (going with FFF here in this case) whatever it may be and then you have the next two from another group (commie, HS or whatever) then you have a few more episodes from FFF again.

JMM does not inform you in any way about this, JMM should try to have one subbing group per series if it can. ofc if something like this gets added then it will also be a way to ignore series that cant help it, like Naruto, One Piece and others that have more than one group working on it like where subbing groups have dropped a series and so on. (your fav groups might drop a series you are watching, but others groups might not be as good as the once you already have) 

this should also check up the releases on AniDB for who have done work on each episode, this could work as a follow function for the user aswell if you give the option to sync periodically.

**Comment by ElementalCrisis** [comment]
Added in Version 3.4.6.2.
