### ISSUE TITLE
clearing search terms are unreliable 

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/jmmclient#122]
Bug: if you "X" out a search term (whatever it may be, a tag, or word or whatever)
if you have backed out of the group filters and find yourself on the main page of the collection tab then it will enter the "All" group filter when you "X" the search term out.
I really don't think it should work like this, it should stay on the same page and not move you to another esp when you have stuff that you don't care that much for in the All filter.
if you stay in a group filter and "X" out the search then it will stay on the same group filter you where in, but it wont stay in your collection hub (main page).

**Comment by jmediamanager** [comment]
This one is not really possible, as when you click on a tag/category etc it has to switch to the "All" category to do a full search.

Clearing the search terms merely clearings the filters.

Getting the result you want requires a major re-work.
So de-prioritizing

**Comment by AreFinstad** [comment]
awww thats too bad. oh well, its not the end of the world really. i just find it annoying at times XD
