### ISSUE TITLE
rescan multiple highlighted file in the unrecognized tab 

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/jmmclient#130]
rescan multiple highlighted file in the unrecognized tab.

we should be able to click and shift click and control click and rescan the highlighted files, we can rehash and ignore the same way but not rescan.
we can only rescan the hole page or one file at a time (should be quicker than this as i Dump alot of files all the time)

![](http://puu.sh/fr7Cz/707595e9df.png)

**Comment by jmediamanager** [comment]
Available in 3.4.3.1
