### ISSUE TITLE
Tract.tv sign in issue

### ISSUE THREAD

**Issue by alph4om3ga** [japanesemediamanager/jmmclient#132]
Since December 27th, My JMM Client hasn't accepted my Trakt.tv account info. I doubled checked with my password and Username via trakt's site, and I have tried this with multiple machines. I am currently running Server: 3.4.2.19, Client 3.4.2.18. This isn't really too important, just something I wanted to bring up as I enjoy this program. I checked to see if someone else posted about this, and I couldn't find anything. I do apologize if I missed something.

**Comment by AreFinstad** [comment]
this issue hasn't been posted before as far as i know.
if i where you i would try to enter your username and password into the JMMServer.exe.Config file that is located inside your server install folder. (you should turn off your JMM server before you do this and then start is up again after saving the text file.) 

got to note that Trakt.tv does go offline quite a bit (almost every day i think) and that can cause problems with login and such, always make sure you can access the site itself in your browser atleast at the same time you try to use it with JMM.

**Comment by jmediamanager** [comment]
Trakt v1 API has been down since about then
I am tracking the upgrade to 2.0 in the following issue.
Until then Trakt support will be broken

https://github.com/japanesemediamanager/jmmserver/issues/116

**Comment by AreFinstad** [comment]
didnt know it was that bad (mostly because i havent watched anime in months XD) thanks for updating us about it! you are great!

**Comment by alph4om3ga** [comment]
Okay, it looks like I should have searched more in the server issues section. I will be waiting for an update then.

**Comment by jmediamanager** [comment]
Closing this for now, track here instead
https://github.com/japanesemediamanager/jmmserver/issues/116
