### ISSUE TITLE
AVDump clear highlighted button?

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/jmmclient#134]
we should be able to clear out the highlighted/marked entries instead of clearing them all or doing it one at a time.

this can work great with issue #131 aswell.

at this moment there is quite some delay when you are clearing/removing one entry at a time and that slows down the hole thing, dont want to wait for each entry to clear out like we have to do now by doing it one at a time.

**Comment by ElementalCrisis** [comment]
There's a Clear List button that does just that.
