### ISSUE TITLE
Problem viewing all variations of a file

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmclient#135]
If an episode has more variations than can be displayed on your screen at the same time there is no way to see the full list and for example mark them as variations so that they don't show up in the Multiple Files utility.

It's not possible to scroll down any more on that screenshot and if there where any other files below it would jump to those instead if you tried to scroll.
There is only a single entity where it happens so it's not very important but worth mentioning.

![image](https://cloud.githubusercontent.com/assets/6645153/6238040/eac50ef8-b74b-11e4-8523-fce73a55ce6c.png)

**Comment by AreFinstad** [comment]
this issue is also happening if there is too many groups for a series aswell. (not just too many file entries) 
have always had this issue with One Piece because of all the subbing groups it has.

**Comment by jmediamanager** [comment]
Fixed in 3.4.3.1
