### ISSUE TITLE
Community Admin - Add Web Browser control to show selected series

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmclient#136]
Community Admin - Add Web Browser control to show selected series side by side when approving a link.

e.g. For TvDB links show the AniDB page and the TvDB page to get an easy preview of what has been selected

**Comment by AreFinstad** [comment]
any news on this? the link system i mean. would love to just help out correcting those things TBH.

**Comment by jmediamanager** [comment]
Yes the TvDB side of it is basically done.
Once I have done Trakt and MovieDB I will give a few more people access to help out (including yourself)

**Comment by AreFinstad** [comment]
did write an edit when you replied, sorry XD sending this comment as it pops up for you

**Comment by jmediamanager** [comment]
Yeah the TvDB side of it works quite well, have also starting adding a few things to make it a bit more user friendly, which will be in the beta

**Comment by AreFinstad** [comment]
will we be able to paste urls into the system? not being limited by the search that JMM does. your normal browsers is alot better for that sort of things IMO and just pasting the link to the series would be a good way to do it over something like thetvdb search is ATM.

**Comment by jmediamanager** [comment]
No, the system doesn't work like that.
Basically every time someone makes a link between AniDB and TvDB, it uploads that link to my Web Cache.

The Community admin system allows you look at all the links people are using, and the pick the correct one(s), and approve them.

Once that is done it will become the community approved link.
e.g to a TvDB link search on 'Ushio to Tora (2015' if you have it.

**Comment by AreFinstad** [comment]
i see, so its its just pulling from what the other JMM guys are using. i guess thats fair. will we be able to force refresh those approven links or something like that? for people that already have wrong links in place and that sort of things. will we also be able to blacklist anidb series from thetvdb searches if they are not on the site or are adult content?

**Comment by jmediamanager** [comment]
I can't force refresh them, some users may not want that for whatever reason
But I have a Trakt Recon working at the moment which will do that (but haven't done it for TvDByet) if the user wants it o.

But when you are importing a new series it uses the Community recommendation first.

**Comment by AreFinstad** [comment]
you could have JMM to download the linking list however you make it, and JMM can compare them to what they have and make a list for the users to confirm changes and so on.... on a per series basis.

**Comment by jmediamanager** [comment]
Yes, that is what I meant for Trakt recon

**Comment by AreFinstad** [comment]
mhm, good to hear. thanks for taking the time for my questions and so on. im off for now, always looking forward for news from you.

**Comment by jmediamanager** [comment]
yeah the bigger problem I am working on at the moment is that after doing a recon between my current Trakt Links, and the latest Trakt database, over 300 of my links are no longer correct.

So I am adding functionality to check all those links and remove them from the database
