### ISSUE TITLE
Program Freezes When Loading My Collection

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmclient#138]
Hello,

For some reason I am unable to view my collection in JMM Desktop. Clicking on any of the populated filter options to view it causes the program to freeze resulting in a force close. I've tried reisntalling JMM Desktop, JMM Server and MySQL multiple times, even tried only adding a single series but still get the same problem. I do have both JMM Server and JMM Desktop installed in a folder called JMM. 

Any help would be most appreciated.

**Comment by jmediamanager** [comment]
Hi, could you please post your logs files for Server/Desktop

**Comment by ElementalCrisis** [comment]
Hello,

Here you go. 
https://mega.co.nz/#!OZ5BlbQB!2aju388UtssMCDYeNLRInEXuH9ggBVPkk0dzaVwRP6U
Include file key

**Comment by ElementalCrisis** [comment]
This issue was resolved when I reinstalled Windows. As the log files are no longer available it will be impossible to track down the exact reason so I'm closing this.
