### ISSUE TITLE
new trakt.tv user will not save 

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/jmmclient#141]
so its a brand new install for the OS and JMM, everything works fine but the Trakt.tv user login.
im getting an error when trying to save it and it wont save in the logs either by the looks of it.

the password and username is correct as i copied it of my LastPass Chrome app that got it saved correctly. 
Logs:
https://drive.google.com/open?id=0B-hww4iUE6HsUU9jRF8xa2Q5Zmc&authuser=0

![](http://puu.sh/gIfCZ/d0e3d25828.png)

**Comment by jmediamanager** [comment]
Closing as a duplicate
https://github.com/japanesemediamanager/jmmserver/issues/116
