### ISSUE TITLE
[Login error] Can't connect to Trakt.tv

### ISSUE THREAD

**Issue by eranor** [japanesemediamanager/jmmclient#145]
Hi.
When I try to connect to my trakt account it gives me an error with failed authentication.
I've tried to use both the username and the email but it does't work either.
Please could you help?

Thanks.

**Comment by AreFinstad** [comment]
this is an issue because Trakt.tv has updates its API and therefor JMM needs to change it aswell to match it. 

this is on the list and already talked about.
https://github.com/japanesemediamanager/jmmclient/issues/141
https://github.com/japanesemediamanager/jmmserver/issues/116

**Comment by eranor** [comment]
Ok. Thanks for the answer.
