### ISSUE TITLE
auto delete leftover groups after series move?

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/jmmclient#146]
could we set the leftover groups that are empty after a move to be deleted on the move? 
i always find that having empty groups like that annoying at times. 
you could do an if statement or something i guess, like when you move the series out of the group and if the group is empty at that point it will delete it. 
ofc it cant delete the group is there is more series in that group tho XD

**Comment by ElementalCrisis** [comment]
Similar to #30.
