### ISSUE TITLE
Custom Tags break on Recreation of Groups

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/jmmclient#147]
Custom Tags broke when i recreated all groups for the place series into the same group option. 
i have filters groups that is set to not show certain custom tags, these was broken on 78 accounts  after recreated all groups earlier today. 
on these accounts it looks like they have custom tags in the UI on a per series basis. but they are ignored by the group filters that want to either have them in them or block them.

removing the custom tag and reapplying them fixes the issue.... but this really should be a problem IMO.

**Comment by jmediamanager** [comment]
Ok this seems a bit strange to me.
The Custom tags are attached to an anime, and not to a specific group.

I suspect the cached data in JMM server was not updated for some reason, but it did work for me

**Comment by AreFinstad** [comment]
well i have had issues with this in general.
if i recreate all my groups to be collected groups (where IP's are grouping up in one Group) it broke the custom tags i already had in place, at times i could see the tag in place of the series and even filter it out (yet it was still there)
only way for me to fix the group filters then was to re-add the custom tag for the group filter to actually block/include the tag.

**Comment by ElementalCrisis** [comment]
Is this still an issue for you @AreFinstad? I was unable to reproduce it.

**Comment by jmediamanager** [comment]
Will re-open if this continues to happen
