### ISSUE TITLE
Feature Request: New filter condition by "at least one file available"

### ISSUE THREAD

**Issue by inaudible** [japanesemediamanager/jmmclient#148]
A large collection of archived anime is stored on a fileserver that I do not keep running 24/7, whilst I try and keep the anime I have still to watch on a local drive. At the moment I only use JMM to scan and keep track of the anime I have on local drives that are on 24/7, so that when I browse for an anime to watch it does not pull up anime on the fileserver that are not immediately accessible.

It would be handy if there was a new filter condition where "at least one file is available", so that I could scan and include the fileserver in my JMM collection, yet be able to filter them out if I want to find an anime which I could immediately watch.

**Comment by jmediamanager** [comment]
While this is possible I don't think it will be practical.
I would need to scan (File operation) at least one file for each series, which would be really slow.

All the other information used in filters is taken from the database

**Comment by inaudible** [comment]
Ah, that's fair enough. Would it be practical to filter by file location instead then? ie. to make a filter that included or excluded all anime where any file is stored on the Z:\ drive for example?

**Comment by jmediamanager** [comment]
Yes that is much more likely, but it would be by import folder.
