### ISSUE TITLE
Keep Getting This Error When Selecting Series

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmclient#149]
Hello,

After recently updating I keep getting this error when I attempt to access the settings tab in JMM. 

![jmm-error](https://cloud.githubusercontent.com/assets/9443295/7549525/a75961a6-f5ed-11e4-8909-88513358b190.jpg)

**Comment by Animeimp** [comment]
Download and reinstall the JMM Desktop.  Then the "There is a upgrade" message should appear at bottom.  Do the upgrade, and the message goes away.

**Comment by ElementalCrisis** [comment]
Did not work, I only get this error on the latest version it seems as I did not encounter it when I reinstalled JMM Desktop before updating it.

**Comment by jmediamanager** [comment]
Can you try downloading the packages, and un-zipping them into the relevant folders

http://www.jmediamanager.org/jmmserver/jmmserver.all.to.3.4.3.2.zip
http://www.jmediamanager.org/jmmdesktop/jmmdesktop.all.to.3.4.3.1.zip

**Comment by ElementalCrisis** [comment]
Sorry for the late response, that seemed to fix my error. Thank you.
