### ISSUE TITLE
Watching Files Outside of JMM Desktop

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmclient#154]
I remember this being brought up before on the old Google code page but I wanted to bring it up again as I had totally forgot and spent the past hour or so wondering why my settings were not working. 

To reiterate the problem, if you want JMM Desktop to keep track of your recently watched episodes, you have to start the episode inside JMM Desktop. Starting any episodes or continuing outside of JMM Desktop does not register the watched flag. 

I know the problem comes from JMM Desktop not running and thus not being able to pull the info from the .ini file in MPC. The workaround would be JMM Desktop pulling the info from the .ini file when starting up but that would only get the last 15 watched files. 

A possibility better idea would be building this function into JMM Server, which is something I believe most people have running in the background. Wouldn't this solve the two problems listed above?

**Comment by jmediamanager** [comment]
I'd prefer not to make it part of JMM Server, since it may not be on the same machine as JMM Desktop.

However I can probably create an option to scan the watch history in your MPC ini file when JMM Desktop starts. It can keep quite a few files there.

**Comment by AreFinstad** [comment]
you can do this with with .nfo files tho, alltho MPC and media players dont really support this, some media servers do. like EMBY for example, they have these lines for watch states in their files that get updated every time someone plays a file with their clients (ofc this works with EMBY's external start aswell with MPC for example)
a more mobile way of doing it will be harder tho, unless we all start syncing to Trakt and other things 24/7.

at this moment JMM does not really work with other media servers at all as well as it could be. things like a standardized folder structure, file renaming that supports the other servers aswell as local metadata (like the watch states.) watch states can also be set to more that one user by having nfo files for each file on the server, there really isnt any limit on it.

also the other servers support trakt so JMM can start making more use of that for its syncing in my opinion, another big thing that will make things smoother for anime fans in general.
support local data, have trakt syncs on every start up of every JMM client and everyone would be in sync with the right watchstates all the time. just my thought on the matter tho.....

**Comment by ElementalCrisis** [comment]
Duplicate of #32 by me not less!
