### ISSUE TITLE
JMM Desktop ignores my cover image settings completely

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/jmmclient#171]
it seems like JMM Desktop ignores my cover image settings completely (hmmmm been a while (like more than a year) since i saw it work)
it always seems like it only loads the AniDB image even tho you can disable that (witch JMM ignores).

**Comment by jmediamanager** [comment]
This seems to work for me.
In which place is it ignoring the setting?

**Comment by AreFinstad** [comment]
just tested this again here, yeah still does not work under the Collection Tab
for the test i disabled every picture except one for this series, i tried refreshing both the series and the list and it will still stay locked. 

only way to change it is to set the image as default (therefor just using one and not rotating between them like atleast i would think it should work) 
if you have no default setting at all it will use the AniDB image even if you deactivate it.
![](http://i.imgur.com/hmVSc1i.jpg)


ignoring completely might be a bit much when i think about it (didnt actually check out the default setting (because i never use it)) 

how i expect it to work is that all the active images would rotate in the list view of the collection tab.

i might be mixing up that it worked before, maybe it was JMM with another program like MP or something..... still think it should rotate active images tho in anycase.

**Comment by jmediamanager** [comment]
Yup have found the issue now, thanks
