### ISSUE TITLE
Blank Poster/Fanart

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmclient#176]
Hello,

I've noticed that while JMM Desktop only downloads the specified amount of Posters and Fanarts, it still shows a blank box for the remaining ones as shown in the screenshot below. 

![extra fanarts posters](https://cloud.githubusercontent.com/assets/9443295/8888480/ec737bc0-3263-11e5-9590-11595a298ee9.jpg)

Unrelated to this issue, as a long time user I'd like to give back in some way and was wondering if you needed help in anything non-programming related? Sometime this weekend I'm gonna get Visual Studio installed and see if my extremely beginner skills can be useful.

**Comment by bigretromike** [comment]
As result of this bug jmm server serve blank images on api request.

**Comment by bigretromike** [comment]
Cure for API: https://github.com/japanesemediamanager/jmmserver/commit/d2bd1fbf43da526fd1e4e892800e767e76269346

**Comment by da3dsoul** [comment]
How would that fix it? It should skip null items, not just fill them with a blank image.

**Comment by bigretromike** [comment]
This way Nakamori when asked for image will get image and not corupted image that breaks cache

**Comment by bigretromike** [comment]
This is because JMMServer function return Stream; it's 100x better than return null;

**Comment by da3dsoul** [comment]
Ah, I see. I'm not sure it would fix this issue though, as it is more related to the way that jmmclient handles displaying null/blank images

**Comment by bigretromike** [comment]
that is true, but this did fix a lot of problem for Kodi :-) which is always a improvement

**Comment by da3dsoul** [comment]
Indeed. Especially for the systems that only have Kodi as a front-end, making cache clearing annoying.

**Comment by ElementalCrisis** [comment]
Fixed and will be available in 3.6.0.1

japanesemediamanager/jmmserver#278
