### ISSUE TITLE
Utility to manage file versions

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmclient#18]
**Reported by werndlymob, Aug 9, 2012**

Utility to manage file versions

A new utility similar to the multiple files utility which allows you to see which files you have multiple versions of v1, v2 etc and delete the older versions

**Comment by AreFinstad** [comment]
close this as its already in JMMD's Multiple Files tab? 
i mean it does display version numbers and lets you delete one of them if you choose. isnt that what this issue is about?
