### ISSUE TITLE
Unwatched episodes counter sometimes doesn't update on addition of new episode.

### ISSUE THREAD

**Issue by CatmanIX** [japanesemediamanager/jmmclient#180]
Sometimes when new episodes are added, the "0 Unwatched" line underneath the number of episodes in the left side thing doesn't change. Even after multiple refreshes and restarting the client and server it still doesn't change. This doesn't happen every time, and it sometimes rectifies itself after a second unwatched episode is added.

I'd provide a screenshot but i don't have any examples to screenshot at the moment since i've watched all the examples >_>

**Comment by jmediamanager** [comment]
There was a change that when in a couple of months back.
Basically the Watched/Unwatched counts no longer get updated immediately when the file is added.
It waits a couple of minutes to see if you are importing any more files before updating it.

This is to help speed up the process of importing large amounts of files for the same series.

Unfortunately if you restart JMM Server it won't end up updating these stats.
I will look at adding something to force update stats in the mean time.

**Comment by maxpiva** [comment]
I'll revise the whole thing, seems is not working right.

**Comment by jmediamanager** [comment]
Thanks maximo

**Comment by maxpiva** [comment]
Okey, i'm ready to take this, leo, i'm thinking on adding a new queue command. Only for this. It's that is ok :)

**Comment by jmediamanager** [comment]
Ok sounds good :)

**Comment by maxpiva** [comment]
Closed by latest pull request to JMMServer.
