### ISSUE TITLE
multi file delete in Unrecognized tab

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/jmmclient#184]
multi file delete in Unrecognized tab.
i think we can use an option to delete more than once file at a time in the Unrecognized tab.
this should be handled the same way as the other highlight options.

also something i think would help the program is building https://github.com/japanesemediamanager/jmmclient/issues/109 into the highlighted options window.
on that note it should either list all crc codes that is parsed and will either have a check-mark or X next to it according to what the parsed crc in the filename matches the actual crc code it hashes. 

i think we should have options with the crc check aswell tho, like if the crc match you can have an option to add to AVDump. if it doesn't it can be added to a list and deleted (i think we should have an failed to download list.... which failed crc files and so on that does not match)

**Comment by ElementalCrisis** [comment]
Can already do this.
