### ISSUE TITLE
www.jmediamanager.org/jmmdesktop/wyserver.zip detected as infected

### ISSUE THREAD

**Issue by Animeimp** [japanesemediamanager/jmmclient#192]
I am getting a Bitdefender error that the website www.jmediamanager.org, and the update file wyserver.zip is infected.  Is anyone else getting this, or is this a Bitdefender false positive?

**Comment by AreFinstad** [comment]
this isnt our program at all (i think).

all the files you need are hosted here: http://japanesemediamanager.github.io/
you will need the server and the desktop to get the most out of it. you can also get a plex plugin if you like that. 

that page isnt really that well done just yet, need some guides and such.... but it shouldnt be too hard.

**Comment by AreFinstad** [comment]
also a note: BitDefender is the ONLY one on VirusTotal that actually flags this site
https://www.virustotal.com/en/url/9ce0966acf6d7b100185af2fa428c6a45644e6b3dff0348bdf81b9d7768954fa/analysis/1439821750/

but for some reason it does not flag it on the file:
https://www.virustotal.com/en/file/daafa0ba3368e13d0d0cf404f8d418dcdf6e5e99f70758f309ca6dd70cbe36a6/analysis/1439821754/


but then again, i dont think this is us at all tho (might be) all talk about JMM and edits and newest files can always be found here on this github.

**Comment by Animeimp** [comment]
The jmm desktop client goes to that URL to check for updates.  The wyserver.zip file as a text file inside that lists the latest versions.

I've been running the jmm server and desktop for almost 2 years now, so I am well aware of what it can do.  :)  Been running the sql server because I have over 1600 series in the database.

**Comment by jmediamanager** [comment]
Yeah as @Animeimp  said, wyserver.zip is used bt JMM Server and Desktop to keep a version history, and allows those programs to detect whether a new version is available to download.

I run AVG myself. but have never had an issue before.

**Comment by AreFinstad** [comment]
yeah, sorry for the coloring of you. but it sounded like you where new and just got to the wrong page XD
