### ISSUE TITLE
More Control Over Series Name

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmclient#193]
I've made a similar request before with #29 but it would be a nice feature if we had more control over the how series name's are displayed. I don't mind and in many cases prefer the original Japanese name is displayed but then I come across a series like Hagane no Renkinjutsushi which is better known to me and I assume a lot of people as Fullmetal Alchemist. Now I can go in and change it manually but what about a multi-series like the Gundam series? According to JMM I have 46 different Gundam series. That's a lot of series and group names I would have to change. If we had the ability to mass change both series name and group names this would greatly help those who'd like to have both Japanese and English names for their collection.

**Comment by AreFinstad** [comment]
ideally we could have a setting that used a ranking system for the names say English>Romanization>Japanese and it would use the name highest on the list first.... unless the user have set the series with another setting manually (an option to set each series name manually (either by changing the priority of the names or by naming it manually with text))

this should also be renaming (or atleast have an option too) the folders of the series for consistency sake.
the renaming script for files also needs work to work like this (dont forget the seasons while you are there :3) 

https://github.com/japanesemediamanager/jmmclient/issues/8
https://github.com/japanesemediamanager/jmmclient/issues/86
https://github.com/japanesemediamanager/jmmserver/issues/84

**Comment by ElementalCrisis** [comment]
We currently do this with the rename all groups function as that also runs the language preference function.
