### ISSUE TITLE
script error in Community Tab (when comparing web pages)

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/jmmclient#195]
im getting a script error in Community Tab (when comparing web pages).
these errors does not show up in either Logs of JMM D. and S.

its nothing serious at all, but it is an error and it does pop up every time i click one of the series in question for review. 

this is obv tied to a script at thetvdb/trakt sites.

NOTE: this happens every time i click a link in the web browser aswell as every time i compare a new series.... so ALOT of times over the time i use the new Community Review Tab.

![](http://i.imgur.com/WgqPouG.png)
![](http://i.imgur.com/d12B16i.png)

**Comment by ElementalCrisis** [comment]
Maybe I'm just blind but how do you access the community tab?

**Comment by AreFinstad** [comment]
you need to be granted access to it.

**Comment by ElementalCrisis** [comment]
Ah gotcha, thanks for clarifying.

**Comment by AreFinstad** [comment]
this is still an issue after newest the update you just released. (3.4.4.3?) also note, you forgot the update the version number in JMMD again :D

**Comment by jmediamanager** [comment]
Where are you seeing the version number for JMMD?
In the about page mine says 3.4.4.3

**Comment by AreFinstad** [comment]
mine says 3.4.4.1 and i updated a few min ago and the program restarted as normal..... hmmm

**Comment by jmediamanager** [comment]
hmmm damn
yeah means it didn't actually update. Might be time to look for some new updater software
You can try running the wyupdate.exe in JMM Desktop folder

JMM Server is now 3.4.4.3?

**Comment by AreFinstad** [comment]
yeah the server is 3.4.4.3.
will update now manually now.

**Comment by AreFinstad** [comment]
it said it was already up-to-date..... so that didnt work XD

**Comment by jmediamanager** [comment]
http://www.jmediamanager.org/jmmdesktop/jmmdesktop.all.to.3.4.4.3.zip

**Comment by AreFinstad** [comment]
now its fixed, and this issue is also fixed and changed :D yay

also, what do you think about an option for using the old compare layout that we had as an option? depending on screen usage im willing to use with JMMD both view options might be good to have, just a thought tho.

**Comment by ElementalCrisis** [comment]
What update software are you using?

**Comment by AreFinstad** [comment]
this im guessing: http://wyday.com/wybuild/help/distribute.php

**Comment by jmediamanager** [comment]
http://wyday.com/wybuild/
Hasn't been updated in years

An option for the old compare might be a bit difficult, but can be raised as an issue

**Comment by jmediamanager** [comment]
This one might be a candidate
https://github.com/Squirrel/Squirrel.Windows

**Comment by jmediamanager** [comment]
Allows support for beta releases, which is something I always wanted (ie opt in to beta releases, and get auto updates)

**Comment by ElementalCrisis** [comment]
Looks good,  I'd say postpone the new update until you get this integrated.

**Comment by jmediamanager** [comment]
I've already done the full release
So if it works for someone great.

But I'll look at this for the next release

**Comment by ElementalCrisis** [comment]
Gotcha, what about creating a new message in JMM?

**Comment by AreFinstad** [comment]
well it looked like the server update worked fine, and yeah.... where just going to say it, send out a mass message about the new update with the DDL link to JMMD.
