### ISSUE TITLE
auto scale TvDB page to fit screen/windows size (atleast 1920x1080)

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/jmmclient#196]
i kind of find it annoying that the compare screen does open theTVDB page zoomed in (or fullsize which it prob is.)
the hole community tab review progress has a few more unnecessary steps for faster usage IMO.
if it where fitting the hole page in width then we would not scroll to the right to find other seasons/all seasons.... something i check every time as i find it easier to compare episode names for best results (safer too IMO) 

another issue on this?
not sure if something like this can be done tho: would it be able to say have the program scroll down to the episode list or something like that. as i find it much safer to compare tho over just series name is pictures. (auto scroll to the episode in question on each site? as i see JMM logs both of these for review, i think it would make things easier and faster this way (could be an optional option too tho)) 

and an issue on this?
also the webpage windows does reload the hole page every time i go to the next season, cant we have JMM detect if there is a change in AniDB or TVDBID before reloading both pages, as reloading them kicks both pages at the top and the reviewer has to find where he was (which is a hassle that can pull people away from using it more. reviewing shows like this for mod usage has to be hassle free and swift and easy to do since we will do it alot)

this is all small things tho and isnt really important, but is for speed and enjoyment of using the review progress IMO.

![](http://i.imgur.com/JmsxM2P.png)

**Comment by ElementalCrisis** [comment]
So i decided to mess around with this. 

![jmmd - community links - anidb](https://cloud.githubusercontent.com/assets/9443295/9576786/0cc4589c-4f90-11e5-93ac-2cf21f32d2e9.png)

![jmmd - community links - tvdb](https://cloud.githubusercontent.com/assets/9443295/9576787/0d0c5e8a-4f90-11e5-9e8e-9b311fa0e423.png)

I've found it much easier to go through and approve with the tabs as I found myself doing less scrolling. 

What do you think @jmediamanager?

**Comment by jmediamanager** [comment]
Yup looks better to me :)

Note - there will always be a few issues because the web browser control is a basically an ActiveX version of Internet Explorer.

I did some changes to replace it with Chromium, but rolled it back as it added about 35MB to the package size.

**Comment by ElementalCrisis** [comment]
OK cool, I'm going to see if I can get the width for the bottom tab the same as the top tab and then submit a commit.

**Comment by ElementalCrisis** [comment]
Fix added in 3.4.4.1.

**Comment by AreFinstad** [comment]
forgot the hotkey tab switches? missing that as using the mouse is slow and slows down the speed one is using on this page.

**Comment by ElementalCrisis** [comment]
Hotkey support would be nice, can you create a new issue for it.

**Comment by AreFinstad** [comment]
i recall you where the one that wanted to do it for me. back when you edited the changes of those tabs.
you also noted that you missed the last release aswell.

maybe im remembering wrongly here. oh well.
