### ISSUE TITLE
skip/decline Linking in Review at the Community Tab?

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/jmmclient#199]
skip/decline Linking in Review at the Community Tab?
at times you can't figure it out if its the right one or not, maybe you need to see the episode in question or something like that but does not have it. in cases like that i think it would be nice to have a skip button ( i guess we can just do another random Anime but...)

or to be able to straight up decline if its wrong.
declining and manual linking goes hand in hand tho IMO
https://github.com/japanesemediamanager/jmmclient/issues/197

number of links i cant approve because either missing info on Date or something similar to actually make a flawless Approval: 3

**Comment by jmediamanager** [comment]
I don't think there is any need to decline a link.
These are just a record of what a particular person has used.

Links which have not been approved are not used anywhere other than the person's collection.
Once a link has been approved, it becomes the community recommendation.

**Comment by AreFinstad** [comment]
very well then, manual linking fixes alot of the issue with this aswell as the reviewer can just choose whatever series/season he would like to actually approve of.
