### ISSUE TITLE
Feature Request: Support For Additional Torrent Programs

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmclient#208]
I no longer use uTorrent and instead now use qBittorrent. However since switching the entire downloads section has become useless for me even though qBittorrent supports WebUI as JMMD is unable to use qBittorrent and just returns an error even though the information is correct and works outside of JMMD. 

If making it so any torrent program will work is not feasible. May I request that support for the top 5 torrent programs be added? 

uTorrent: Already Supported
Deluge: http://dev.deluge-torrent.org/wiki/Faq#WebUI1
Transmission: https://trac.transmissionbt.com/wiki/WebInterface
qBittorrent: https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation
Tixati: I know it supports it but couldn't find any documentation on it.

**Comment by AreFinstad** [comment]
we already have an issue about adding qBittorrent https://github.com/japanesemediamanager/jmmclient/issues/53

also note that you only have Desktop Torrent Clients there.... something that isnt that popular with Highend Seedboxes being so cheap nowadays.
i for one have not used a normal Torrent Client in over a year as they are slow, are limited by my upload speed and so on. + i find using DDL from the Seedbox with JDownloader being a really good option (as doing DLL from a Seedbox with a gigantic line makes you use your full bandwidth all the time no matter what) 

yeah you have to pay for it, but people cant see what you are downloading as you do NOT connect to the Torrent at all (atleast here in Norway they have started monitoring people by downloading Torrents themselfs (as another random user) and then logging the IP's which they could use in later years)
yes a VPN does fix alot, but that does not seed for you, it does usually make your connection slower (and ping higher) 

if you want to check out a seedbox that is cheap and just works, here: https://put.io/


i for one throw in a vote for put.io support, here is their API: https://put.io/v2/docs/index.html

**Comment by ElementalCrisis** [comment]
I completely overlooked seedboxes, that would also be a good idea for people with limited upload speeds.

**Comment by AreFinstad** [comment]
not just for limited uploads, faster uploads. like 200MB/s big. well that is the highest i have gotten from Put.io which is loads better than the 100/15Mb/s i have >___<

**Comment by bigretromike** [comment]
Tixati is cancer :-) 
but im +1 for qBittorent - sadly it use different WebAPI than uTorrent which is also cancer of bittorrent clients :-) but it works.

**Comment by ElementalCrisis** [comment]
Similar to #53, going to close all torrent program support issues and make #53 the main issue for it.
