### ISSUE TITLE
Keep Pinned Series

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmclient#214]
Currently when you pin a series, the pinned series only lasts until you close the program. It would be better if a pinned series stayed pinned until you remove it.

**Comment by AreFinstad** [comment]
have been discussed before, wont happen.
you can always use Custom Tags to have them "Pinned" all the time.

**Comment by ElementalCrisis** [comment]
The way I was using the pinned feature was for series that needed fixing. Tags is a good idea, I just made a custom playlist and added them to it.

**Comment by AreFinstad** [comment]
yeah, i used to use the pinned tab for series on high prio on my watchlist..... thats why i asked for a push towards custom tags :D

**Comment by jmediamanager** [comment]
Yeah I think this is something you can achieve easily with custom tags?

**Comment by ElementalCrisis** [comment]
Oh yeah definitely, I didn't even consider custom tags when I wrote this thread but after @AreFinstad suggested them I realized it was a much better solution.

**Comment by jmediamanager** [comment]
Ok cool, closing
