### ISSUE TITLE
Idea For Getting More People Active With Updating Series Data

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmclient#215]
I don't have any stats to back this up but I think if it was clearly stated in JMMD that episode information and images come from TvDB and a link to show them how to add it, we might see more people filling in the missing data over at TvDB. For example if the episode was missing the image, there could be a link saying something like "Episode image missing, click here to add" which would redirect the user to a page in the online documentation showing how to add missing images. I'm not sure on where this button/notice would best fit but it would be worth it if people started filling in the missing data.

**Comment by AreFinstad** [comment]
already have an issue on this one, has been around some time now, 
Metadata in general needs more encouragement for users to update them.

some issues that might interest you:
https://github.com/japanesemediamanager/jmmserver/issues/77
https://github.com/japanesemediamanager/jmmclient/issues/88
https://github.com/japanesemediamanager/jmmclient/issues/86
https://github.com/japanesemediamanager/jmmclient/issues/83
https://github.com/japanesemediamanager/jmmclient/issues/90

**Comment by ElementalCrisis** [comment]
Well good to know I'm not the only one who thought of this. If I could get Visual Studio to stop giving me a "Resx is not supported in a Windows Presentation Framework (WPF) project" error I would try and see what I could do to help. Until then back to the documentation.

**Comment by jmediamanager** [comment]
What version of VS do you have?
I am currently using VS2015

**Comment by ElementalCrisis** [comment]
Visual Studio 2015 Express for desktop. I can open and modify the resx file but get that error when viewing the different forms.

**Comment by jmediamanager** [comment]
oh yeah you will get errors all the time.
Try making sure JMM Server is running when you are using JMM desktop

Also all editing of the forms is done in XAML arther than using the designer

**Comment by ElementalCrisis** [comment]
So keep JMM Server running when editing JMM Desktop, gotcha. 

I'm used to seeing what's being edited via designer, helps me get a better idea of what I'm doing. Make sense that the reason I'm getting that error is because it's not being used. Now that I know that it's time for a lot of trial and error.

**Comment by jmediamanager** [comment]
Sometimes the designer will work and some times it won't :(

All editing is done best via the XAML anyway though
