### ISSUE TITLE
search window does not scale with amount of community links

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/jmmclient#224]
search window does not scale with amount of community links, i think the community links should be just one or two lines and we should be able to click it to enlarge it for the hole list.

also, the window does not scale.
![](http://i.imgur.com/7044l3Q.png)
![](http://i.imgur.com/Ajo235J.png)

**Comment by ElementalCrisis** [comment]
For the Search Window for Community Recommendations a max height could be added so the ListBox uses it's scroll bar. 

![jmmd - search window](https://cloud.githubusercontent.com/assets/9443295/9725241/1cbf9e2e-5598-11e5-801f-f365216488ad.png)

It works but makes the Community Recommendations a fixed height and not scalable, I'll keep playing around with it to find a better solution.

**Comment by ElementalCrisis** [comment]
For now I'm gonna leave it like that, if you like it Leo I'll submit a commit for it. Not shown but I also added a link next to Community Recommendation that links to the documentation explaining what Community Recommendations are.

**Comment by jmediamanager** [comment]
Yup I think the way you have suggested it, is the best way.

**Comment by ElementalCrisis** [comment]
@ AreFinstad 
When you say the window does not scale are you referring to the TvDB and Trakt TV panels as seen in your screenshot?

**Comment by AreFinstad** [comment]
the search window yeah, i meant that the actual size of the window would scale to fit the info needed, im fine with having a long list of all the approved tags (as it gives us the info about what you are accepting) but the window should scale to fit all that info without needing to extend it manually.
limiting the approved links to a few lines isnt the right way IMO, it could have a short and long version where the user can toggle between it (like the description of episodes and so on) that will make the list shorter and also remove the need for having a larger window.

**Comment by ElementalCrisis** [comment]
I thought of something similar but ran into a problem, for series like One Piece the Community Recommendations box is just going to keep growing. 

This is what it looks like fully extended.
![jmmd-search window full display](https://cloud.githubusercontent.com/assets/9443295/9734390/840530f4-55e7-11e5-8ac0-db9462fb0e26.png)

Even with a toggle you'd still run into a similar issue. The only solution I came up with is making the search window a certain height and having an scroll bar that would scroll the entire window instead of each section. This is something that seemed like a lot of extra work when you could define the height of the Community Recommendations box allowing the user to scroll through the list of community recommended links.

**Comment by AreFinstad** [comment]
hmmm well the only reason we have the approved links there that way is to show the info that is being used, how about we could have a tab/page that just handles such things (changes of links and so on over what the user have ATM) and have a button that opens that tab kind off how the community tab is doing, only for the end users side of things. 
having something like this removed the hole approved links list from that window (that is already too small) while still keeping the info somewhere else, ofc we still need one line for the button and such to be placed.

bake it into the community data tab or something like that maybe? IDK, i really think the info the approved links gives you is good as more info the user have the better understanding the user will also have. we need the info somewhere, it doesnt need to be located there tho..... in the issue window we only need an use approved button and that should be enough IMO.

**Comment by ElementalCrisis** [comment]
All the info is still there, you just need to scroll through it. Moving it to the Community tab would not work as normal uses don't have access to the community tab. I would say download the source, compile it and give it a try or if you'd like I can try and make a patch so you can see the changes in actions.

**Comment by AreFinstad** [comment]
fair enough, also there is a difference between the Community Tab (review tab) and the Community Data Tab.

**Comment by ElementalCrisis** [comment]
Sorry, misread Community Data tab as Community tab.

**Comment by ElementalCrisis** [comment]
This was addressed in the last update, so this thread can be closed.
