### ISSUE TITLE
stop reloading web pages if the ID's are the same

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/jmmclient#225]
stop reloading web pages if the ID's are the same, not if you are still on the same side (incase you go into seasons and so on (you should not reload the page for that)).

this is getting me banned from AniDB webpages (not JMM AniDB usage tho) so i cant open any more web pages on JMM or chrome. 

reloading the page also moves you back to top aswell as going back to the main series page instead of seasons and so on (scrolling up every time is bad for AniDB as the episodes are at the bottom)(and Seasons is on another page on tvdb)

so if the ID's are the same as the last one you had up in your browser compare it should not reload the pages (maybe have a reload button? (or enable F5 reload while mouse is in the window))

**Comment by AreFinstad** [comment]
found a workaround, by highlighting the link list i can go down to approve everything without actually having JMM reloading the page (also does not give me the loading error as the page does not get reloaded) 

this workaround makes things MUCH faster as it does not reload and does not give me the error every time i click a link. should be done by everyone that review links till the system is smoother.

**Comment by AreFinstad** [comment]
thought about this, this should also go across all Metadata Tabs (across TVDB and Trakt)

also the Review process does only enable review of one AniDB ID at a time, therefor does NOT need to reload the tab (ever really unless you move on to another review)

**Comment by ElementalCrisis** [comment]
I agree with this, got me banned from AniDB for a bit as well.

**Comment by AreFinstad** [comment]
well, try my workaround, works great.... but only if there is 3 or more links tho XD (if they all are in line) as it does load every link you click (but does not load if you have them marked and then approve of them :D

**Comment by jmediamanager** [comment]
Sorry guys, will work on this next
