### ISSUE TITLE
when hitting Random Anime and Searching in Community Review Tab it should open in All Linking Sites

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/jmmclient#226]
when hitting Random Anime and Searching in Community Tab it should open in All Linking Sites.

if you hit random series it does only open the AniDB ID in whatever Site tab you have open at the time (either TVDB or Trakt), it should in the other hand open the same AniDB ID in all (both for now) sites we can link.

this will work great with Manual linking aswell IMO https://github.com/japanesemediamanager/jmmclient/issues/197

**Comment by jmediamanager** [comment]
This is intentional to reduce the amount of load.
What I have done a few days ago, but not in the beta yet is that I auto populate the Search box with the AniDB ID, so that you just need to press search.
