### ISSUE TITLE
Linking Tile says all links are Approved over Approval Exists if all match Approved Links

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/jmmclient#229]
Linking Tile says all links are Approved over Approval Exists if all match Approved Links.
i mean we should have another piece of Text and maybe another icon (green checkmark) if all links match the Approved Links (for all AniDB files).

right here:
![](http://i.imgur.com/a2IIqXZ.png)

in the picture i do have all AniDB files linked and all links are approved (there is links in the review list that is wrong tho) yet it says Approval Exists eventho there is no more files to approve.

**Comment by ElementalCrisis** [comment]
I think its just a check and shows Approval Exists if there is an approved link regardless if you have it linked correctly or not.

**Comment by jmediamanager** [comment]
Yes, only the community admins see those highlighted areas.

So it is meant as a flag to admins to indicate whether this series looking at or not.
In the future I will add something for all people which will let them know that their links are incorrect.

**Comment by AreFinstad** [comment]
i just want something that tells me with a glance that the links match whatever is approved or not while also giving the info about no approved links aswell.

**Comment by AreFinstad** [comment]
while its by design i think it should show another message if you match what is approved (all of your links match across) 
right now it only says if something is approved or not, not if you actually match what is approved. a small thing but gives more clarity to the user.
