### ISSUE TITLE
Random Series Tag List Does Not Show Tag Filter

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmclient#231]
Noticed this when I was messing around with the random series window.
![jmmd-random with scrollbar](https://cloud.githubusercontent.com/assets/9443295/9565990/8a2b0948-4ea5-11e5-99b6-a6a6434f8c5b.png)

The selected tag filter (All or Any) is not shown.

**Comment by jmediamanager** [comment]
This was probably broken when AniDB switch from Genres to Tags

**Comment by ElementalCrisis** [comment]
Fixed in 3.4.4.1.
