### ISSUE TITLE
Tag Description Not Being Updated

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmclient#237]
So I was working on #56 when I noticed that the tag description doesn't seem to get updated even when running Update AniDB Info. 
![jmmd - tag description issue](https://cloud.githubusercontent.com/assets/9443295/9749258/3fa6e0d4-5640-11e5-93e1-0abb62aa6c83.png)

Also seems it's truncating the description, maybe adding a wordwrap would work better?

**Comment by jmediamanager** [comment]
Actually the mismatch in description seems to be an issue on AniDB itself.
http://anidb.net/perl-bin/animedb.pl?show=tag&tagid=1700&reltb=animetb

However there are some issues on JMM side which I will I found while look at this.
