### ISSUE TITLE
MAL watched stats dont update

### ISSUE THREAD

**Issue by merlinx2k** [japanesemediamanager/jmmclient#238]
Hi, 

the watched stats from MAL stoped updating. If i add a new series it will be added to MAL but everytime i set an episode on watched it would not update the info on MAL. I tried the the button under Server "Upload watched stats to MAL" but it does nothing. I see the queue at the bottom and it seems to do something, but after it is done nothing changes on the website itself. If i look under "Utilites->Logs" nothing shows up, except the usual AniDB updates.

I tried updating to the Beta version but it did not solve the problem. Maybe MAL changed something? Any help is apriciated, thanks in advance ;)

P.S. sorry for my bad english.

**Comment by ElementalCrisis** [comment]
Try changing an episode that is already marked as watched to unwatched and see if it updates. Then check the logs in the JMM Server (in the folder called logs) and see if the change in watched status is listed.

**Comment by merlinx2k** [comment]
i tried it and the server shows following log that indicates an update send to MAL, but on the website the update did not show.

[2015-09-09 23:39:12:321] Info|BackgroundWorker.WorkerThreadStart => CommandProcessorGeneral.workerCommands_DoWork => CommandRequest_MALUpdatedWatchedStatus.ProcessCommand Processing CommandRequest_MALUpdatedWatchedStatus: 11082

**Comment by ElementalCrisis** [comment]
Maybe, let's summon @jmediamanager. I'll also setup a MAL account when I get home to give it a try.

**Comment by jmediamanager** [comment]
Yeah I'll have to take a look.
I know MAL broke their API a while back, but I haven't tested it since

**Comment by ElementalCrisis** [comment]
Did some testing, linking a series in JMM Desktop has it show up on MAL but attempting to change any info causes problems. I've got a backlog of queued commands in JMM Server as every time I try to delete them, JMM Server freezes. It never gets past "Syncing MyList info from HTTP API".

**Comment by merlinx2k** [comment]
thanks for testing it and confirming its not a problem on my end ;) - hopefully its easy to fix.

**Comment by ElementalCrisis** [comment]
Well it took some time but cleared the commands, no update on MAL but AniDB updated with no problems. Taking a look around it seems MAL's API is pretty poor from what I've read in a dozen or so threads of people asking for updates to it. I did find this though, https://bitbucket.org/ratan12/atarashii-api

**Comment by ElementalCrisis** [comment]
Fixed in 3.6

https://github.com/japanesemediamanager/jmmserver/pull/332#event-734683616
