### ISSUE TITLE
Comments from Users always empty

### ISSUE THREAD

**Issue by t0815** [japanesemediamanager/jmmclient#240]
hi, i just noticed, that no comments are shown in the tab at all. I checked the DB and see that 
comments do exist for a certain show.

Comments Tab:

![recommendation_bug_1](https://cloud.githubusercontent.com/assets/10379828/9795280/fe0a2404-57ef-11e5-84c6-0e7e10a8ee41.jpg)

has entry in DB:

![recommendation_bug_2](https://cloud.githubusercontent.com/assets/10379828/9795282/02239002-57f0-11e5-908b-edcf40a69bab.jpg)

**Comment by ElementalCrisis** [comment]
Some additional info, only happens on the comments tab in collections, under Metro the comments show up.

**Comment by AreFinstad** [comment]
just for input sake, this also happens to me :/

**Comment by jmediamanager** [comment]
Confirmed
