### ISSUE TITLE
Incorrect text for Trakt Update button in collection tab

### ISSUE THREAD

**Issue by Darken5** [japanesemediamanager/jmmclient#245]
Just a little typo i noticed.
![jmm typo](https://cloud.githubusercontent.com/assets/9792820/9837397/1228d6e8-5a0b-11e5-9fe6-b20d34934fdc.png)
Should say 
"Update

Download fresh data from Trakt TV and
update the local database"

Dunno if the button actually works for Trakt or TvDB. something to look into.

**Comment by ElementalCrisis** [comment]
Probably just a mistake with the tooltip.

**Comment by Darken5** [comment]
thats what it looks like, just thought i'd point it out.
