### ISSUE TITLE
Connection to Trakt via Pin and Authorisation not working

### ISSUE THREAD

**Issue by yhoogi** [japanesemediamanager/jmmclient#247]
Trying to enable Trakt via the new pairing feature is not working.
Entering the received PIN results in below error message
Tried it with firefox & Internet Explorer

Cheers,

![trakt](https://cloud.githubusercontent.com/assets/10504005/9899223/b6e9a6ae-5c58-11e5-98c8-30b2c3f06291.jpg)

**Comment by jmediamanager** [comment]
Are both your JMM Server and Desktop version 3.4.4.3?

**Comment by yhoogi** [comment]
It is 4.3.3.3 for Desktop & 4.3.3.2 for Server.
I don't see a new server version

Cheers

**Comment by jmediamanager** [comment]
Looks like the auto updater is having issues again. Can you manually update the files?
Just copy over the top of you existing files

http://www.jmediamanager.org/jmmserver/jmmserver.all.to.3.4.4.3.zip
http://www.jmediamanager.org/jmmdesktop/jmmdesktop.all.to.3.4.4.3.zip

**Comment by yhoogi** [comment]
got now successful pairing

Thanks
