### ISSUE TITLE
sort and/or filter unrecognized files tab.

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/jmmclient#254]
hey can we get some refined management in the unrecognized files tab?
like sort by import date, file size, and if CRC code is correct from what it parsed from the filename?
also a filter that allows entering the hard-drive letter and/or full folder path so only files will show from that folder and bellow.
(say if i type in V:\JMM Source in the filter/search bar at the top, it would remove all unrecognized files in the tab that ISN'T within that folder or bellow it (inside it))

**Comment by misakitchi** [comment]
I want this feature too! :)
