### ISSUE TITLE
No season or episode information available when linking some series with Trakt

### ISSUE THREAD

**Issue by CatmanIX** [japanesemediamanager/jmmclient#256]
Currently trying to connect Read or Die with it's [trakt listing](https://trakt.tv/shows/r-o-d-the-tv-1969), but JMM isn't showing any seasons or episodes available even though they're certainly available on the webpage:

![](http://i.imgur.com/oZMJvE4.png)

I saw this with another series previously but can't recall which one, so it's not an isolated issue, however that's only two out of hundreds of series that has had this problem for me so far so it's definitely not common either.

**Comment by CatmanIX** [comment]
Found the other series i had this issue with, forgot i noted them down in a scratch pad.

[Gankutsuou: The Count of Monte Cristo](http://trakt.tv/show/gankutsuou-the-count-of-monte-cristo)
[After War Gundam X](https://trakt.tv/shows/after-war-gundam-x-1996)

**Comment by ElementalCrisis** [comment]
Read or Die has an incorrect Trakt link, that's why you can't select anything. The real link is http://trakt.tv/movies/r-o-d-read-or-die-2001. Pretty sure that's the error with the other two as well though I can't check them on AniDB as I'm hashing a lot of files.

**Comment by CatmanIX** [comment]
Uh, no, the one you linked is the incorrect link, the one i'm trying to use is the one that actually has data.

**Comment by ElementalCrisis** [comment]
I don't use Trakt but doing a search only shows that entry. Can you link me to the correct one?

**Comment by CatmanIX** [comment]
https://trakt.tv/shows/r-o-d-the-tv-1969

It's also the link in my opening statement.

**Comment by ElementalCrisis** [comment]
Yeah I switched to my computer from my phone an realized there was a link in your original message.

**Comment by jmediamanager** [comment]
Confirmed

**Comment by CatmanIX** [comment]
Any idea why it's having issues with these shows in particular but not any others?

**Comment by jmediamanager** [comment]
The Runtime field is NULL instead of having a valid number

**Comment by jmediamanager** [comment]
Fixed for next release.
NOTE - I have also approved the TvDB and Trakt links you submitted

**Comment by CatmanIX** [comment]
>NOTE - I have also approved the TvDB and Trakt links you submitted

...I don't follow, what links?

**Comment by jmediamanager** [comment]
When you linked the AniDB tv series to the TvDB/Trakt series, it submits it to the Web Cache
I then used your links to be the officially correct links.

If anyone else adds this series to their collection they will automatically use those links now without needing to search. If they do search they will see this

![image](https://cloud.githubusercontent.com/assets/6645153/10570171/ce92d996-767b-11e5-8ad7-78536f744cee.png)

**Comment by CatmanIX** [comment]
Oh, i didn't know you had to approve that manually, i figure it just went by consensus or something.
