### ISSUE TITLE
Collections Tab - Have the "All Filter" shown by default

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmclient#26]
Collections Tab - Have the "All Filter" shown by default

**Comment by ElementalCrisis** [comment]
Agreed, being able to select which filter is shown by default is better than my original suggestion.

**Comment by AreFinstad** [comment]
this is a dupe IMO. it should be closed and moved to https://github.com/japanesemediamanager/jmmclient/issues/5 
as that issue covers default group filters in general..... and can make the all filter show as default aswell as stated by this issue.
