### ISSUE TITLE
Pinning Series

### ISSUE THREAD

**Issue by t0815** [japanesemediamanager/jmmclient#264]
hi there,

maybe a little improvement. If you pin a series and there already is that series pinned, maybe dont open a new tab, but just jump to already existing one instead?

Would be good imo.

**Comment by jmediamanager** [comment]
yup good idea

**Comment by AreFinstad** [comment]
hmmm maybe have JMM to look for dupe tabs on that pinned tab?
so it never makes another one of the same one and if there is a dupe it would do as the OP says and open the one already open. 

also to note on the pinned tab, small sorting function maybe? 
sort by last added to pinned, sort by name, sort by last added file date for example.
