### ISSUE TITLE
Strange missing/ available file stats since last version

### ISSUE THREAD

**Issue by t0815** [japanesemediamanager/jmmclient#265]
not really sure if this is a bug, but i noticed some strange behaviour on file availability stats.
case 1:  i have all currently available file for a series from a release group i am collecting. But in overview it still tells me, 1 missing file.

case 2: for some other series i dont have all files from release group i am collecting. They are not available yet (or never will :D). But in overview, it just tells me "x unwatched". Missing episodes are not recognized somehow (from other groups).

**Comment by jmediamanager** [comment]
For case 1, I am putting this on hold until the next version is release soonish
http://japanesemediamanager.github.io/changelog.html

For Case 2, is it possible you can show me in a screenshot?

**Comment by t0815** [comment]
sure. On an additional note: I had files from other release groups for those missing files before, but deleted them. Maybe group info about this files gets delteted too, dunno.

Screens:

![series_scr_a](https://cloud.githubusercontent.com/assets/10379828/11040393/4a529814-870c-11e5-843e-660d9d9a6e66.png)

![series_scr_b](https://cloud.githubusercontent.com/assets/10379828/11040399/521768ea-870c-11e5-9a50-ab1ec01e405f.png)

**Comment by jmediamanager** [comment]
There is a new release out now, download and try pressing the "Update All Stats" button.
Wait until the queues are empty and check if Case 1 is fixed

**Comment by t0815** [comment]
worked! Updating all Stats solved case 1 and 2!

**Comment by jmediamanager** [comment]
Great :)
