### ISSUE TITLE
Trakt support broken again?

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/jmmclient#273]
i think the trakt support is broken again, searches does not show any results at all.
manually copying over parts of the URL seems to not gather season or episode data at all either and makes it unusable as you cannot link anything.

**Comment by jmediamanager** [comment]
I believe it is related to the refreshing of the auth token.

Can you try authorizing again, and then see if it works?
I have seen this happen on my machine, but can't replicate it at the moment

**Comment by AreFinstad** [comment]
yeah..... that was it, sorry for that. didnt think about it XD oh well. close the issue or would you like it to stay open for sake of making a message appear or something for the user when it has issues like that?

**Comment by jmediamanager** [comment]
no leave it open, still need to fix the issue

**Comment by CatmanIX** [comment]
Ahh, didn't even think of that, was about to raise the same issue.

Definitely should be some kind of message alerting you about that.

**Comment by jmediamanager** [comment]
This is fixed in 3.4.6.4
