### ISSUE TITLE
duplicates of same file

### ISSUE THREAD

**Issue by bond4u** [japanesemediamanager/jmmclient#274]
JMM desktop 3.4.6.2 but I've seen that also in earlier versions.
"Multiple files" lists two files with same name in same folder (drop destination in case of screenshot)
![jmm-dups](https://cloud.githubusercontent.com/assets/66413/12019979/845ceb4c-ad7f-11e5-9886-a84dd09977ef.png)

**Comment by AreFinstad** [comment]
plz make sure that both of the files are the same, for one of them is a different version. the other might be a different version or just have a different hash value and that is it.

there is an AniDB link on each file that you can click to checkout the info about the file to check for difference.

im 98% sure that all 4 of those files are different and JMM is functioning like it should.

when people add info to AniDB they can make mistakes as could have forgotten to use a version number and so on when adding the info to their servers.

**Comment by bond4u** [comment]
Yes, anidb links reveal that they have different hashes.
I was wondering why it simply overwrites the file.
Quite often I delete one entry and then discover later that I lost the file.
![image](https://cloud.githubusercontent.com/assets/66413/12026200/9bcb76be-adbf-11e5-971b-14bb306a4364.png)
Maybe loosing a file can be prevented when two entries link to same file?

**Comment by AreFinstad** [comment]
if you dont delete the entry of the file in the JMM DB then JMM will think its there eventho the file isnt.

the reason it tried to overwrite is because the filename is the same because HorribleSubs sucks and to be frank shouldnt be used unless there is no other fansubber out there for that show. 

you can easily set up a auto file rename script with JMMD that will rename the file for you in a fashion you like so it never gets overwritten again (therefor will always show up with JMMD's duplicated and multibe managers).

one other way tho alot slower and more manual work is to delete the file locally then press the "Remove Missing Files" button in JMMS or in JMMD\Server.

**Comment by bond4u** [comment]
Well, I'd like to add CRC to filename if it's not present, but that's not how renaming works?
Following script didn't work for some reason:
"IF G(7172) DO ADD ' [%CRC]'"
Crc was not added to filenames. Tried the other way:
"IF G(!7172) DO FAIL
DO ADD ' [%CRC]'"
but too many files got crc.

**Comment by AreFinstad** [comment]
i always feel that any file should have a crc no matter what as esp HorribleSubs in general does not contain that at all.

a simple line like: 
``` DO ADD '[%CRC]' ```
will add a crc value to every file.


tho if you like more of a finished managed look to your filenames then i would use something like my own script:

it will look like this like a final product:
SeriesName - Episode Number - Version Number (if it has any) Cen (if censored) - Episode Name [Group Name][CRC32].container

for example: Demon King Daimao - 10  - Akuto`s Great Capital War [Seto Otaku][CE560666].mkv
```
IF I(eng) DO ADD '%eng '
IF I(ann);I(!eng) DO ADD '%ann '
// Episode Number, don't use episode number for movies
IF T(!Movie) DO ADD '- %enr '
// If the file version is v2 or higher add it here
IF F(!1) DO ADD 'v%ver'
IF I(cen) DO ADD %cen
DO ADD  - %epr
// Sub group name
DO ADD ' [%grp]'
DO ADD '[%CRC]'

// Replacement rules (cleanup)
DO REPLACE '' '' // replace spaces with underscores
DO REPLACE 'H264/AVC' 'H264'
DO REPLACE '0x0' ''
DO REPLACE '__' '_'
DO REPLACE '__' '_'

// Replace all illegal file name characters
DO REPLACE '<' '('
DO REPLACE '>' ')'
DO REPLACE ':' '-'
DO REPLACE '"' '`'
DO REPLACE '/' '_'
DO REPLACE '/' '_'
DO REPLACE '\' '_'
DO REPLACE '|' '_'
DO REPLACE '?' '_'
DO REPLACE '*' '_'

```

but as i said, a simple ``` DO ADD '[%CRC]' ``` should do it TBH.
