### ISSUE TITLE
login for bakabt.me is broken

### ISSUE THREAD

**Issue by catchra** [japanesemediamanager/jmmclient#275]
[2016-01-03 16:32:43:580] Trace|EventRoute.InvokeHandlersImpl => DownloadSettingsBakaBT.btnTest_Click => TorrentsBakaBT.Login =========================================================== 
1 cookies found.
=========================================================== 
#1> Name: bbtid	Value: f8buq2bq135484idg7ir9rmda4	Domain: bakabt.me	Path: /	Exp: 2/2/2016 4:32:42 PM

**Comment by ElementalCrisis** [comment]
BakaBT login has been fixed by @Baine with https://github.com/japanesemediamanager/jmmclient/pull/286. However both Search and Browse need to be updated as well. Search and Browse reported here, https://github.com/japanesemediamanager/jmmclient/issues/287.
