### ISSUE TITLE
Quirk with Queen's Blade TvDB/MyAnimeList Linking

### ISSUE THREAD

**Issue by Darken5** [japanesemediamanager/jmmclient#283]
Just noticed something weird when trying to link any Queen's Blade series to TvDB or MyAnimeList. Anytime I try to use the search feature with the title from AniDB already in the search bar, nothing shows up. Deleting the : and everything after it, still no results. Have to manually type in Queen's Blade for any results to show up.

Example:
```
Queen`s Blade: Utsukushiki Toushi-tachi     (copied directly from the search bar) Doesn't work.
Queen`s Blade                       Doesn't Work
```

```
Manually typing in:
Queen's Blade                         Works.
```

See the difference? first one (from AniDB) has the " ` ", typing it out, you'd use " ' " which TvDB and MyAnimeList recognize

`
'

Is there any way to filter that key out? or recognize it and search both it and the alternate '  ?

Very minor issue. Just pointing out this little quirk.

(Sorry about "code" boxes, was getting weird text with the weird apostrophe)

**Comment by ElementalCrisis** [comment]
Related to #46, the grave accent is what's causing the problem and is used by AniDB for legacy reasons. See https://tracker.anidb.net/view.php?id=828 for more info. 

Some kind of condition that automatically turns grave accents into apostrophes when searching would be ideal.

**Comment by ElementalCrisis** [comment]
Fixed, will be available in the next version of JMM.
