### ISSUE TITLE
Searching for torrents on Baka

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/jmmclient#284]
searching in jmmd for "Nekomonogatari" no results.
searching in webbrowser at baka, got results.

There is no login/password anywhere to enter and search is a bit cut down without proper sign in

**Comment by ElementalCrisis** [comment]
That's right, I forgot BakaBT requires an account to search. Would love to see this added.

**Comment by bigretromike** [comment]
sorry, im probably blind

**Comment by ElementalCrisis** [comment]
I missed it at first as well.  :)
