### ISSUE TITLE
BakaBT and AB Search and Browse Broken

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmclient#287]
Searching and browsing with BakaBT and/or AnimeByt.es selected will not return results. @Baine was able to fix the login issue for BakaBT (https://github.com/japanesemediamanager/jmmclient/pull/286) but more work is needed to get searching and browsing working again.

**Comment by ElementalCrisis** [comment]
Currently being worked on by Baine, #286.

**Comment by Baine** [comment]
login, browse, search, opening website (where applicable) and downloading torrents for both should be fixed in #286, and only wait to be merged. although it would be safer if someone else would test that fork before merging...
