### ISSUE TITLE
Request to add Nyaa Sukebei to torrent search

### ISSUE THREAD

**Issue by TheOne320** [japanesemediamanager/jmmclient#288]
I request to add http://sukebei.nyaa.se/ to the torrent search list.

**Comment by ElementalCrisis** [comment]
My thoughts on this would be to have to separate entries, Nyaa and Nyaa Sukebei that way were not combing regular and adult content into one search.

**Comment by ElementalCrisis** [comment]
Alright so I have it searching/browsing Sukebei. Will submit a commit for it later.
