### ISSUE TITLE
One-Click Title Switch

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmclient#29]
**Reported by rickyvh001, Oct 19, 2012**

Seeing how it pulls the list of titles for the series from AniDB, it would be a nice addition if you could click one of the alternative titles and have it automatically change the series and group title to what you selected.

**Comment by ElementalCrisis** [comment]
After manually renaming 10 different series so far, I would love for this option to be added in a upcoming release.

**Comment by ElementalCrisis** [comment]
You can close this, I just recently discovered this feature was already built-in, just in a different way. The title switch button works fine and when I originally submitted this request this was one of the methods I had in mind. I've added a tooltip to override to explain this just in case anyone else misses it like I did.
