### ISSUE TITLE
Remove AnimeSuki Option In Downloads 

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmclient#290]
Considering AnimeSuki no longer lists torrents with the last entry in their release section being from 2013 I think it's time for that site to be removed.

**Comment by da3dsoul** [comment]
I say leave it for completion's sake. It's not like it causes any issues

**Comment by ElementalCrisis** [comment]
Seems redundant when you have Nyaa, BakaBT, AnimeBytes and TT available and still updated.

**Comment by da3dsoul** [comment]
Does AnimeSuki use a different server? When nyaa went down it was a mess and redundancy is welcome in times like those.

**Comment by ElementalCrisis** [comment]
AnimeSuki no longer provides tracking for torrents, from their website.

> AnimeSuki.com Torrents
> All torrents that used to be on this page have been moved to Prutser.com. The reason for this so that >AnimeSuki.com can now honestly claim it absolutely does not host any file and can focus on being >just an index of anime torrent links. Just the location of the torrents has changed: the tracker and >torrents themselves remain unchanged. 

Prutser.com is no longer around and redirects to AnimeSuki which means nothing will show up anymore in JMMD.

**Comment by da3dsoul** [comment]
Weird, I swear I used it last week. I might've been spacing and used TT. Well, if it's broken and can't be fixed, remove it I guess.

**Comment by ElementalCrisis** [comment]
So you can still preform searches. 
![jmmdesktop_2016-04-19_23-31-04](https://cloud.githubusercontent.com/assets/9443295/14665283/d6d4fb20-0686-11e6-92fb-d015b00ccf2f.png)
But downloading the file shows it's from NYAA.

**Comment by da3dsoul** [comment]
Hmm, might be able to use it to fix nyaa searching then.
