### ISSUE TITLE
Download missing episodes airing anime

### ISSUE THREAD

**Issue by CtrlAltDefeat94** [japanesemediamanager/jmmclient#297]
When I go to Downloads -> Missing episodes the option is there to search/list all missing episodes of currently airing anime. When I select this option and let JMM search, I get no results returned even though I know I do miss some episodes of still airing shows.

Probably unnecessary, but here's a screenshot either way;
![qx3gxbm 1](https://cloud.githubusercontent.com/assets/5640470/13230971/e419a828-d9a7-11e5-9d25-54c0a573e152.png)

**Comment by ElementalCrisis** [comment]
Hmm, just tried all the different Airing State filters and options, works fine for me. Does the same thing occur when using the Missing Files utility under the Utilities tab?

**Comment by CtrlAltDefeat94** [comment]
Doesn't seem to work under the utilities tab either

**Comment by ElementalCrisis** [comment]
Jump on Discord and send me a message and we can test somethings.

**Comment by CtrlAltDefeat94** [comment]
I'm not really sure how discord works(just created it), could you send me a message instead? username is CtrlAltDefeat

**Comment by ElementalCrisis** [comment]
Sure, first you'll need to join the server.
https://discord.gg/0XKJW7TObKLajoKc

**Comment by ElementalCrisis** [comment]
So an update on this.

The Missing Files utility basically just complies a list of the current missing episodes, as in episodes already marked by JMM as missing. Adding a series with missing files registers correctly as the series is imported checking your files with AniDB. However, removing episodes from series does not register even though JMM shows the file missing on the episode tab. Running Remove Missing Files updated JMM showing the file is misisng and the episode is listed under Missing Files. You can manually update the series AniDB info or wait until JMM does it automatically, only then will new missing episodes show up.

**Comment by jmediamanager** [comment]
When you say "remove episodes from a series", does this mean you just deleted a file in windows?
Or did you delete the file from JMM Desktop?

**Comment by ElementalCrisis** [comment]
In my test I removed it in Windows and restarted JMM Sever + JMM Desktop.

**Comment by jmediamanager** [comment]
Yeah no real way to fix this, it's the reason we have the 'Remove Missing Files' button in the first place

**Comment by ElementalCrisis** [comment]
Yeah that makes sense, gonna close this issue.
