### ISSUE TITLE
German Translation unsounded in most cases

### ISSUE THREAD

**Issue by miracle152004** [japanesemediamanager/jmmclient#303]
German Translation is unsounded in most cases. It reads itself like a direct translation of every word instead of a context based translation. Or a tool was used to import the translations and the tool swapped resources around.

Here a few examples(in the following order english - german current [translation to englisch] - german better):
1. Continue Watching... (Recently Watched) - Weiter beobachten... (Kürzlich gesehen) [Continue Monitoring (Recently Watched)] - Weiter ansehen... (Kürzlich gesehen)
2. Collection - zu vermeiden. [avoid] - Sammlung 
3. Essential - Ätherische Öle [ethereal oils or essential oils] - Erforderlich

These are only the most prominent I have seen until now. There are many more.
I will look into this and fix it when I see them.

**Comment by ElementalCrisis** [comment]
All translations are machine translations, allows us to include additional languages even if they are not the best. Users will be able to submit updated translations soon which will be included in future versions of JMM.

http://jmediamanager.org/translate/
