### ISSUE TITLE
Remember Location During Refresh

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmclient#31]
**Reported by rickyvh001, Nov 2, 2012**

While viewing your collection, when clicking refresh it jumps to the first series in your collection. It would be nice if when it refreshed, it remained on the series you were looking at.

**Comment by ElementalCrisis** [comment]
As I've been going through and fixing up my collection, this is something I'd like to see implemented.

**Comment by ElementalCrisis** [comment]
Fixed in next version of JMM.
