### ISSUE TITLE
New Group Filter - Most Recent Episode Air Date

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/jmmclient#313]
For handling recent shows. As of now, a not accurate workaround is setting Air Date to 100 days (season is 90+10 for 13 episode or baseball interruptions). This doesn't work for >12 episode shows, and at the end/start of seasons, it gets messy.

Another similar one that could be simple enough is Finished Airing Date.

PS. I wasn't sure whether to put this on Desktop or Server, but since groups are created and handled in the desktop application, I picked here.

**Comment by da3dsoul** [comment]
I've been working on this the past day or so. I see why no one jumped right on it. A lot more work than it seems. Updating Database schemas, adding the condition, adding api, finding safe places to set the value, etc

**Comment by da3dsoul** [comment]
Yay, almost done. Testing and Debugging!  I'll need someone with (or just more familiar with) SQLite and SQL Server to check my schema update code

**Comment by ElementalCrisis** [comment]
I gave it a shot as it seemed easy but it's way above my current skill level. :)

**Comment by da3dsoul** [comment]
I can wrap my head around just about anything, but the time it takes to completely familiarize myself with the full codepath in something so involved takes...a while.

**Comment by ElementalCrisis** [comment]
Oh wow, missed your update. Awesome job! 

I have a lot of free time now with school over so I'll start teaching myself again. I know there's been a couple similar requests for additional filters you might want to take a look at. Not sure how hard or easy they would be to add.

**Comment by jmediamanager** [comment]
Out of interest, what schema change did you make?
Without looking at the code right now, I think this could be done without it.

**Comment by da3dsoul** [comment]
I added LatestEpisodeAirDate to AniDB_Anime

**Comment by da3dsoul** [comment]
Prevents the need to recalculate it every time a filter request is made...

**Comment by jmediamanager** [comment]
Ok, the alternative is just to add it to the stats cache.
And then you would only have to calculate it at startup, and then update it whenever you update the anime record.

**Comment by da3dsoul** [comment]
I'm just now finding out that "LatestEpisodeNumber" is not always calculated... :(

**Comment by da3dsoul** [comment]
Okay, there is something very wrong with the way LatestEpisodeNumber is calculated. I'm running an AniDB, and 
```
SELECT LatestEpisodeAirDate,LatestEpisodeNumber,MainTitle FROM anidb_anime
Where LatestEpisodeNumber is not NULL
```
is returning fewer results after anime is scanned

**Comment by da3dsoul** [comment]
Well, I'll let my anidb scan finish, and then continue after I have some decent debug data

**Comment by da3dsoul** [comment]
K I'll need to fix the bug with LatestEpisodeNumber not populating, then this should work.

**Comment by da3dsoul** [comment]
woot fixed it. Testing more to make sure everything works

**Comment by da3dsoul** [comment]
https://github.com/da3dsoul/jmmserver/tree/Last-Aired-Date
https://github.com/da3dsoul/jmmclient/tree/Last-Air-Date
I got everything to populate on the SQL side, but for some reason, the group filter does nothing. Can you take a look?

**Comment by da3dsoul** [comment]
Found out the problem is purely on the client side, as kodi shows the proper results. Will keep working on it!

**Comment by da3dsoul** [comment]
Fixed it! Yay. Now to make it a sort filter...much later.

**Comment by da3dsoul** [comment]
Merged and closed
