### ISSUE TITLE
Nyaa Downloader Broken

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/jmmclient#314]
I tried a random ([HorribleSubs] Naruto Shippuuden - 456 [720p].mkv) file from anime Suki to see if it worked at all. I'm using the latest commit as of 4/14/16. The log seemed to have a malformed URL in which it converted all special characters to percent codes, including the important ones (/?&=)

**Comment by ElementalCrisis** [comment]
I think this was introduced in 3.5, I'll ask @jmediamanager to look into this.

**Comment by jmediamanager** [comment]
Nyaa change the format of their HTML slightly
