### ISSUE TITLE
Cant scroll in JMM desktop AvDump

### ISSUE THREAD

**Issue by rashid19961** [japanesemediamanager/jmmclient#319]
![untitled](https://cloud.githubusercontent.com/assets/18513200/14586789/ce9fa0b4-04b4-11e6-9053-60547a9a3094.png)
Cant scroll after Adding many anime list in Avdumb jmm desktop

**Comment by da3dsoul** [comment]
Is that before or after hitting the dump files button? It won't respond after. At least it doesn't lock up the whole program like most of the buttons.

**Comment by rashid19961** [comment]
It doesnt motter really, when i choose few files i can scroll and add the video to anime but when i choose a huge amount of video it doesnt let me scroll

Note: it happend after The dumb
