### ISSUE TITLE
Marking Episodes As Watched That Were Watched Outside Of JMM Desktop

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmclient#32]
**Reported by rickyvh001, Nov 2, 2012**

Currently in order for an episode to get marked as watched you have to have clicked the play button inside of JMM Desktop. Seeing how it pulls the data from the MPC .INI file, would it be possible to have it so if you watch episodes outside of JMM Desktop. The next time JMM Desktop starts up it checks the .INI file and marks any episodes watched as watched in your collection?

**Comment by ElementalCrisis** [comment]
This is more of a change to the media player being used and not JMM Desktop. This feature is available is using Nakamori, Plex Plugin or My Anime 3.
