### ISSUE TITLE
JMM Skipping Files During Import

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmclient#321]
Multiple users have reported an issue with JMM not always adding all files in their import folders. Files that are skipped do not show up in unrecognized either. Users have reported trying to move the affected files to different import locations, issue still remains.

**Comment by jmediamanager** [comment]
This is not really much info to go on.
Are there any logs I can look at?

**Comment by ElementalCrisis** [comment]
I'm not sure if it's the exact same problem but here are the logs from a user on the forums.
http://jmediamanager.org/forum/thread-11.html
https://drive.google.com/file/d/0Bx7ztabL111uc0xYTFR3bHpaWms/view?pref=2&pli=1

**Comment by ElementalCrisis** [comment]
I'm going to close this issue and mark it as not a bug. I've been unable to reproduce after adding and removing thousands of files. JMM even picked up non-anime files. If anyone is having this problem check your unrecognized files for the missing files. If it's still an issue make a new issue and provide as much detail as possible and include the logs.
