### ISSUE TITLE
Downloading a torrent with special characters from "Search Torrents" create an empty file

### ISSUE THREAD

**Issue by d3xMachina** [japanesemediamanager/jmmclient#323]
If you try to download a torrent file that contain special characters like "&" from the "Search Torrents" in "Downloads", it creates an empty torrent file in the torrent black hole folder.

Moreover the name of the torrent is not properly displayed in JMM Desktop. By example the character "&" get replaced by "& amp;" (without a space).

If you want to try by yourself search for "Capeta" on Nyaa and check the biggest file which contains a "&".

**Comment by ElementalCrisis** [comment]
It's been fixed. 
https://github.com/japanesemediamanager/jmmclient/issues/314
