### ISSUE TITLE
IndexOutOfRangeException

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/jmmclient#324]
When in the collection, under Continue Watching (System), if you are viewing the last show, and mark it as watched. It'll give the message. Pretty minor, but it's there.

**Comment by ElementalCrisis** [comment]
Added 10 random shows to the Continue Watching (System) filter and was able to mark the last show on the list as watched with no error messages. 

1. Can you reproduce the error each time and if so can you post your logs? 
2. What version of JMM (Desktop & Server) are you running?

**Comment by da3dsoul** [comment]
I'm running latest commit on both. I'll see about those logs.

**Comment by da3dsoul** [comment]
Couldn't seem to reproduce this. I'll reopen it if happens again and I catch the log
