### ISSUE TITLE
Recursively group related series

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/jmmclient#327]
There are shows that are related, but not all are listed on every show. For example, A certain magical index is related to index ii, the index movie, railgun, railgun SS, etc. When running the regroup script, it will separate them inconsistently depending on the order it scans them in. Sometimes railgun will be included, sometimes it won't, depending on if it scans index or index ii first. To prevent flooding AniDB, only scan shows you have. It'll be less accurate that way, but if you are like me and care that much about it all being grouped, you probably have all of it that matters to group it properly.
And because this will take more thinking, it should all be in a task that's not on the main GUI thread...

**Comment by da3dsoul** [comment]
I happened to find the spot for this while working on other stuff. I'll do it.

**Comment by da3dsoul** [comment]
I'm noticing this is already done. The scan only checks the first group returned by relation, rather than merging the multiple groups using a missing link.

**Comment by da3dsoul** [comment]
It's better now. The Monogatari Series managed to only split into two groups, rather than 4. Gotta group 'em all! I'm sorry.

**Comment by da3dsoul** [comment]
Yay I fixed it! I also added another setting that allows for vague grouping (all of ghost in the shell, macross, gundam, etc). Still need to make GUI for setting it, though.

**Comment by ElementalCrisis** [comment]
Awrsome! It will be nice not having 40 different entries for Gundam. :)

**Comment by da3dsoul** [comment]
Ikr, it grouped Sao and accel world. I was kinda surprised, but it makes sense as it is alternative setting in the same universe

**Comment by ElementalCrisis** [comment]
Might want to add a setting to not group alternate settings. :)

**Comment by da3dsoul** [comment]
Well, it already has the option to not group them, as the default ignores same setting.
Accel World https://anidb.net/perl-bin/animedb.pl?show=anime&aid=8691
Gundam https://anidb.net/perl-bin/animedb.pl?show=anime&aid=715

The formats for grouping don't really allow for it to group gundam but not accel world

**Comment by maxpiva** [comment]
Yepz, just my tought. We should have a default grouping settings, all checked except,  alternate and character turned off, otherwise. It'll be a mess on some groups.
Examples: Fate Stay Night
Durradara

**Comment by ElementalCrisis** [comment]
Oh OK I see, small price to pay and easy to fix for better series grouping.

**Comment by ElementalCrisis** [comment]
@maxpiva That does seems like best option. Let the user decided how strict the grouping is.

**Comment by da3dsoul** [comment]
https://github.com/japanesemediamanager/jmmserver/blob/master/JMMServer/Entities/AniDB_Anime.cs#L2244 is how it is already. I made it a separate setting to ignore that. We could have a small separate section with checkboxes. How's that?

**Comment by ElementalCrisis** [comment]
Yeah, that would work. Have it default at prequel, sequel, ova and Movie and have the other relation options available to be checked

**Comment by da3dsoul** [comment]
I'll set it up as exclusion, but yes with the standard as default.

**Comment by ElementalCrisis** [comment]
Sounds good!

**Comment by maxpiva** [comment]
Anyway, the main grouping problem, is we cannot recursive get all the series grouping because AniDB will ban us. Because of that the system will only group the related series you have. The problem is, when you have two or more sets of series that are grouped together, but they re not grouped as one, because there you're missing the series that links those groups together.

**Comment by da3dsoul** [comment]
I'll check the code path, but it can fairly easily be made to only use the web cache. Naturally, if the missing link is not there, it won't download and thus not be grouped. At least in my case, if I'm worried about a show being grouped, I'll manually click the download missing data button, or just download the missing show. Worst case scenario, I could add relations to AniDB

**Comment by da3dsoul** [comment]
BAM! This after running the Recreate script.
![screenie](https://dl.dropboxusercontent.com/u/31454410/Github%20Issues/Screenshot%202016-05-20%2016.41.37.png)

**Comment by da3dsoul** [comment]
Hey @ElementalCrisis, I just remembered...I despise making UI.... Would you do the check box thing?
I have the setting set up as a '|' separated list of lowercase strings. By default "same setting|alternative setting|character|other" and this lovely evaluator:
```
public static Boolean isRelationTypeInExclusions(string type)
        {
            string[] list = ServerSettings.AutoGroupSeriesTypeExclusions.Split('|');
            foreach (string a in list)
            {
                if (a.ToLowerInvariant().Equals(type.ToLowerInvariant())) return true;
            }
            return false;
        }
```
This is the commit to my fork. https://github.com/da3dsoul/jmmserver/commit/2c9ca24cbdde5f9194f70427efa7401db8338a58

**Comment by ElementalCrisis** [comment]
Sure, I'll take a look later tonight.

**Comment by da3dsoul** [comment]
```
        // The actual server setting
        private string autoGroupSeriesRelationExclusions = "";
        private string AutoGroupSeriesRelationExclusions
        {
            get
            {
                return autoGroupSeriesRelationExclusions;
            }
            set
            {
                autoGroupSeriesRelationExclusions = value;
                OnPropertyChanged(new PropertyChangedEventArgs("AutoGroupSeriesRelationExclusions"));
            }
        }

        private bool isRelationInExclusion(string relation)
        {
            foreach (string a in AutoGroupSeriesRelationExclusions.Split('|'))
            {
                // relation will always be lowercase, but a may not be yet
                if (a.ToLowerInvariant().Equals(relation)) return true;
            }
            return false;
        }

        // local dummy for ease and aesthetics
        // this is what path will be pointing to
        // repeat and replace "same setting" with desired
        public bool RelationExcludeSameSetting
        {
            get
            {
                return isRelationInExclusion("same setting");
            }
            set
            {
                if(value)
                {
                    if(!isRelationInExclusion("same setting"))
                    {
                        AutoGroupSeriesRelationExclusions = AutoGroupSeriesRelationExclusions + "|same setting";
                    }
                } else
                {
                    if (isRelationInExclusion("same setting"))
                    {
                        string final = "";
                        foreach(string a in AutoGroupSeriesRelationExclusions.Split('|'))
                        {
                            // add all except value and fix any uppercase
                            if (!a.ToLowerInvariant().Equals("same setting")) final += a.ToLowerInvariant() + "|";
                        }
                        // this will be "" if all are unchecked
                        // remove last '|' added in previous loop
                        if(!final.Equals(""))
                        {
                            final.TrimEnd('|');
                        }
                        AutoGroupSeriesRelationExclusions = final;
                    }
                }
            }
        }
```
There are some instructions in the comments there. Insert this at Line 1435 in JMMServerVM.
For the first example coded out, 
`IsChecked="{Binding Source={x:Static local:JMMServerVM.Instance},Path=RelationExcludeSameSetting}"` for your checkbox

**Comment by da3dsoul** [comment]
insert these as well...assuming you want these checkboxes to do anything. still in jmmservervm
after line 337
`this.AutoGroupSeriesRelationExclusions = contract.AutoGroupSeriesRelationExclusions;`
after line 459
`contract.AutoGroupSeriesRelationExclusions = this.AutoGroupSeriesRelationExclusions;`

The updated contracts are on my github in the standard impatience. I'll be making a PR soonish.

**Comment by da3dsoul** [comment]
This is done and prs have been made and tested. I did trace the code path and it will not flood anidb. It will, however, not group completely if you are missing a show that acts as a link in a chain of sequels eg hanamonogatari in the monogatari series.

**Comment by da3dsoul** [comment]
https://github.com/japanesemediamanager/jmmserver/pull/262

**Comment by da3dsoul** [comment]
This is fixed in maxpiva's pr
