### ISSUE TITLE
Mark as watched dont work

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/jmmclient#330]
with 3.5 both server/client on clean database with added few files for testing, when I pick series from collection, all , series name and in the view without switching it to the tab like view click 'eye' icon it dosn't change anything in that view, but the anime goes to "continue watching' on dashboard. Refresh button dont change anything.
The view on episode tab after switching it works ok

This is on sqlite database on newest compilation from github.

**Comment by jmediamanager** [comment]
I'll investigate

**Comment by da3dsoul** [comment]
Indeed, the eye doesn't work, but the mark all as Watched does work

**Comment by ElementalCrisis** [comment]
I believe this was fixed in #365, can you confirm @bigretromike.

**Comment by bigretromike** [comment]
yup, fixed
