### ISSUE TITLE
Client stats on Server status are behind by several seconds and always "Idle"

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/jmmclient#335]
Have a screenie!
![Screenie FTW](https://dl.dropboxusercontent.com/u/31454410/Github%20Issues/Screenshot%202016-04-30%2005.31.10.png)

**Comment by ElementalCrisis** [comment]
Was reported on Discord, @jmediamanager is looking into it.

**Comment by da3dsoul** [comment]
Kk

**Comment by da3dsoul** [comment]
Fixed in maxpiva's pr
