### ISSUE TITLE
User Settings very broken

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/jmmclient#336]
I don't know where to start. The only user ever visible is 'Default'. Any changes only affect 'Default'. Add new user button doesn't add new user. Add new user button resets all gui items for user settings (name, anidb, admin, etc) to blank. Even when editing the SQL db to add a new user, it doesn't show up or become editable.

**Comment by ElementalCrisis** [comment]
Just checked, bug present in 3.5 as well.

**Comment by da3dsoul** [comment]
Oh, yes, I forgot to mention I'm on latest commit

**Comment by da3dsoul** [comment]
You can select the manually added user (via SQL) in the status bar button

**Comment by da3dsoul** [comment]
The commit didn't seem to fix anything. Try adding a user and you'll see what I mean. I can now also confirm this happens on MySQL and SQL Server

**Comment by ElementalCrisis** [comment]
Works fine.

![jmmdesktop_2016-05-10_12-22-24](https://cloud.githubusercontent.com/assets/9443295/15159582/36b8185a-16aa-11e6-9cbe-b65440939531.png)
![mysqlworkbench_2016-05-10_12-24-41](https://cloud.githubusercontent.com/assets/9443295/15159583/36d53430-16aa-11e6-8b4d-1472a4ba8a1b.png)

**Comment by da3dsoul** [comment]
Ah ha. Thanks

**Comment by ElementalCrisis** [comment]
I'll add a note to clear up any confusion.

**Comment by jmediamanager** [comment]
@da3dsoul  Is this working for you?

**Comment by da3dsoul** [comment]
Yes it does work

**Comment by da3dsoul** [comment]
It lags for a second, but it works, and it is not an every day function, so who cares if lags.
