### ISSUE TITLE
'Server Status' is not sync between server and client

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/jmmclient#343]
When pause anidb queue on server (because auto ban) the client wont display that, for him its running and hitting pause button dont do anything there.
When pausing via hand Hasher same thing

**Comment by da3dsoul** [comment]
probably dup or related to #335

**Comment by bigretromike** [comment]
In my case they not behind. Only not refresh button status. Numbers are ok

**Comment by da3dsoul** [comment]
Ah OK

**Comment by bigretromike** [comment]
Buttons just don't synchronize. Image/command counters are fine

**Comment by ElementalCrisis** [comment]
With 3.6 is this still an issue for you @bigretromike?

**Comment by bigretromike** [comment]
nope, it have been fixed
