### ISSUE TITLE
Server Status not displaying messages on 3.5.0.2

### ISSUE THREAD

**Issue by pandabuilder** [japanesemediamanager/jmmclient#348]
Server Status block on JMM Desktop displays the number of tasks running, but no longer display the description of the current one
![server_status](https://cloud.githubusercontent.com/assets/11399675/15416496/0eb0c2c2-1e1a-11e6-85c8-90735f82104b.png)

**Comment by da3dsoul** [comment]
Dup of #335

**Comment by jmediamanager** [comment]
Yup
