### ISSUE TITLE
Hang when clicking on any item in AVDump

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/jmmclient#352]
For several seconds, regardless of state.

**Comment by naarcissus** [comment]
I've had this issue too. Once I couldn't get much of the program to respond for almost a minute and had to exit and start again.

**Comment by da3dsoul** [comment]
Yep, that's what happens. Restart doesn't help for me

**Comment by ElementalCrisis** [comment]
No problem at all on my end when i tried a couple nights ago, tried with multiple files of varying size. Wonder what could be causing the issue for you two.

**Comment by da3dsoul** [comment]
After cracking open the debugger and placing _many_ breakpoints, I've found what takes the most time is finding a matching show based on string for something you've never added before (or had info downloaded for).

**Comment by da3dsoul** [comment]
When you have a decently sized library

**Comment by da3dsoul** [comment]
A solution would be to make any reference to this
```
    AllAnime.Clear();
    foreach (AniDB_AnimeVM anime in AniDB_AnimeVM.BestLevenshteinDistanceMatches(dump.VideoLocal.ClosestAnimeMatchString, 10))
    {
        AllAnime.Add(anime);
    }
    if (AllAnime.Count > 0)
        lbAnime.SelectedIndex = 0;
```
run in a background worker and have a small label say it's working. Then if you feel like finding it faster and select something yourself, cancel the background worker. At least that way, if you know it's going to take forever to find (or not) a result, you can still do things.

**Comment by da3dsoul** [comment]
A temporary workaround for single files is to manually link them and then avdump. That gets messy for full shows though, as there are no batch operations in the manually linked page

**Comment by ElementalCrisis** [comment]
I'll need to doublecheck but I'm pretty sure you can batch add manual links.

**Comment by da3dsoul** [comment]
You can batch add them. You can't perform any batch operations once they've been linked. The way around this is to add them to the avdump queue, then manually link them. After that they'll be added to the library and it won't take as long

**Comment by da3dsoul** [comment]
You still need to unlink and rescan them

**Comment by ElementalCrisis** [comment]
I'll need to doublecheck but I'm pretty sure you can batch add manual links.

**Comment by da3dsoul** [comment]
This line took 35s for me. I know @maxpiva is already working on it, but that is quite a while.
```
List<JMMServerBinary.Contract_AniDBAnime> animeRaw = JMMServerVM.Instance.clientBinaryHTTP.GetAllAnime();
```

**Comment by da3dsoul** [comment]
This is fixed now
