### ISSUE TITLE
Missing Icon for 12bit.

### ISSUE THREAD

**Issue by naarcissus** [japanesemediamanager/jmmclient#357]
![screenshot - 2016-05-26 20_33_54-jmm desktop](https://cloud.githubusercontent.com/assets/3468111/15597159/76bbc552-2382-11e6-8acb-869df01fb108.png)

I assume 14 and 16bit is also like this.

**Comment by da3dsoul** [comment]
I don't really understand why such a thing exists. There are no 12-16 bit displays. 10 bit displays are hard enough to get

**Comment by da3dsoul** [comment]
The best you get is the same idea of super sampling.

**Comment by naarcissus** [comment]
Yeah, Deridiot and Worf at AniDB were pretty appalled as well.

**Comment by da3dsoul** [comment]
Well whatever. It's easy enough to implement if anyone really cares.

**Comment by da3dsoul** [comment]
That's also a terrible anime to have in 12 bit. The images aren't in decent enough color spectrum to matter. No Game No Life, K, and Kotetsujou no Kabeneri would be fantastic, though.

**Comment by ElementalCrisis** [comment]
I added support for 12 bit and 8 bit since it was missing. Commit will be up in a bit.
