### ISSUE TITLE
Manually Deleting Group/Series Refreshes Filter List Showing No Items

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmclient#378]
When this happens, you have to go back to the main filter list and reload the filter for the filter list to populate again. In addition, clicking the refresh button does nothing either. 

HOW TO REPRODUCE:

1. Navigate to Collection and select a filter that has items in it.
2. Delete a series or group. 

EXPECTED BEHAVIOR:
When a series or group is deleted, the list refreshes showing the filter contents, not an empty filter.

**Comment by maxpiva** [comment]
Fixed #385
