### ISSUE TITLE
Manually Adding New Series/Group Does Not Initially Show Up

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmclient#380]
You have to go back to the main filter list and reload the filter list for the series/group to show up in the filters. In addition, clicking the refresh button does nothing either. 

HOW TO REPRODUCE:
1. In collection click New Group, fill out information and click Save.
2. You are taken to the All filter, however your added group does not show up. 

EXPECTED BEHAVIOR:
Added group should be visble when taken to it.

**Comment by maxpiva** [comment]
Fixed by #385
