### ISSUE TITLE
Language Preferance Not Respected Or Displayed Correctly.

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmclient#381]
Some groups/series will have their name changed to match language perference while others will not. Some groups will have their name changed but the series inside the group will not. Some series in a group will have their name changed but the group will not. 

HOW TO REPRODUCE:
1. In Settings > AniDB under Language Preferance change the top language as htis is the one that will be used first.
2. Click Renanme All Groups.
3. Once down click Collection and All filter. 

EXPECTED BEHAVIOR:
All groups and series should have their name in the selected language only defaulting to the 2nd language if the group/series name is not available in the first language.

**Comment by ElementalCrisis** [comment]
Being worked on by @da3dsoul.

**Comment by da3dsoul** [comment]
Internally, it's all named properly. I think it's a contract update issue.
