### ISSUE TITLE
Icon Does Not Change When Pausing/Unpausing A Command

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmclient#382]
Additionally, the text is shown in the OS language and not the selected language in JMM Server/JMM Desktop. 

HOW TO REPRODUCE:
1. Pause a command (Haher, AniDB, Image)
2. Resume the paused command

EXPECTED BEHAVIOR:
Icon should update to reflect current command status and wording should reflect selected language in JMM Desktop, not Windows.

**Comment by hidden4003** [comment]
I tried fixing this.
1. Buttons do work, they are just delayed until next server status update, so up to 4 sec. delay but I guess that is working as intended?

2. I tried fixing the translations, but the value itself comes from the server. Server is sending text value and that value is used as is and I did just check that if you select server language as RU then you get RU status text in english client.

**Comment by ElementalCrisis** [comment]
I don't remember it taking as long as 4 seconds to update, best way would be to compare with an older release. The OS language is taking priority over the selected language, JMM in German yet status updating in English.

![bainejmmdesktop](https://cloud.githubusercontent.com/assets/9443295/16374776/ea3c7ac4-3c0c-11e6-92bf-6c6605f2fc50.png)

We have this problem before so I'm assuming something with the cache update changed our previous fix. I'll keep looking into it.

**Comment by hidden4003** [comment]
I've made buttons more responsive.
Now the bad part. As soon as you switch server language to non-English buttons break because they determine status by analyzing the text for a word "pause", in other locales there is no such word so button gets stuck in pause state indefinitely.

**Comment by ElementalCrisis** [comment]
Would adding those strings in JMM Desktop help?
