### ISSUE TITLE
Error When Moving Series Into New Group

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmclient#391]
When attempting to move an existing series into a newly created group I receive the following error. 

![jmmdesktop_2016-06-25_23-20-00](https://cloud.githubusercontent.com/assets/9443295/16360826/6e63ec16-3b2b-11e6-98e5-2c1ba8ee5ce3.png)

The series is still moved into the selected group. I've also noticed this only happens on groups with a single series, you can move a series out of a group with no error message as long as there is at least one other series still in that group.

**Comment by ElementalCrisis** [comment]
@maxpiva I'm still getting this error after recompiling with your changes.

**Comment by maxpiva** [comment]
Yepz, the thread is still fucking around. Now the move series is working. Will retest.
