### ISSUE TITLE
Manually Created Groups Not Usable Until Restart

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmclient#392]
Any group that is manually added is unable to have any series moved into it until JMM Desktop is restarted. These groups also don't show up on the move group list either.

![jmmdesktop_2016-06-25_23-26-56](https://cloud.githubusercontent.com/assets/9443295/16360846/68678e20-3b2c-11e6-97c9-99d9d15c4a13.png)

**Comment by bigretromike** [comment]
Also manualy added group filter is not usable with API without restarting Server
