### ISSUE TITLE
Changing Language Adds Duplicate Continue Watching (System) Filter

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmclient#394]
If you change the language of JMM Desktop and/or JMM Server and then restart both, it will add a duplicate Continue Watching (System) in the new language instead of updating the exsisting filter.

![pythonw_2016-06-24_04-52-42](https://cloud.githubusercontent.com/assets/9443295/16365734/2242bcde-3bbe-11e6-8656-689e14c2034c.png)

**Comment by hidden4003** [comment]
I've tried reproducing, changing server language causes "Continue watching" filter to be recreated. Changing client language does nothing. So it is a server issue.

**Comment by hidden4003** [comment]
This was fixed in the server https://github.com/japanesemediamanager/jmmserver/pull/320
