### ISSUE TITLE
Watch status button image not changing when clicked

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmclient#40]
**Reported by Craige1Emmott, Jan 15, 2013**

Sometimes the watched status button does not change its picture from the watched state to the unwatched state and visa versa, even if the actual watched state has changed. The pictures will change to the correct state if the page is reloaded. (noticed on the anime episode's tab)

**Comment by ElementalCrisis** [comment]
Can reproduce but it's so random, not sure what is causing it.

**Comment by ElementalCrisis** [comment]
Fixed, will be available in the next version of JMM.
