### ISSUE TITLE
Modifying Users Speed Issue

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmclient#402]
In Settings > User attempting to make any changes by adding/removing a user or modifying an existing user causes JMM to temporarily freeze for at least 10 seconds while your change is being processed. Using a SQLite DB on both and on 3.5.0.2 the same operations take less than a second.

**Comment by maxpiva** [comment]
Wait should be added, on big collection, every groupfilter need to be calculated for the new user. Or if the user changed the hidden categories. etc. So time maybe 10 seconds or 2 minutes.

**Comment by da3dsoul** [comment]
You should prolly add a change checker to it, to only recalculate all that if it is changed.

**Comment by maxpiva** [comment]
In fact there was a bug in there, now it'll update on category changes and new user.

Anyway, we should add a busy to JMMClient.

**Comment by ElementalCrisis** [comment]
Seems recent updates have fixed the speed problem, closing.
