### ISSUE TITLE
JMM Desktop - Freezes when user is added

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmclient#41]
**Reported by imperialxt, Jan 16, 2013**

*What steps will reproduce the problem?*
1. Add a new user (just default settings no admin etc)
2. Window will go to not responding
3. Dance like it's 1969!

*What is the expected output? What do you see instead?*
A new user should be created(which it is kinda I think) but it should create the user without freezing up.

*What version of the product are you using? On what operating system?*
3.1.28 - Win 7 x64

**Jan 20, 2013 werndlymob**

Yes the user is created, but the process takes quite a long time to complete as it creates all the user specific records for series/episodes.

I will change it to run on a background thread.

**Comment by ElementalCrisis** [comment]
As this feature works as intended (just takes some time) I'm changing this to Enhancement - Feature Improvement.

**Comment by AreFinstad** [comment]
i think there should be a confirmation popup window that tells you about this taking time and so on while you can confirm your action. 
unless you do it on a background thread that works smoothly in the back that is.

**Comment by ElementalCrisis** [comment]
No longer an issue on 3.7
