### ISSUE TITLE
Series With Multiple Approved Links Not Getting All Approved Links Added

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmclient#418]
I've noticed that if a series has multiple approved community links, only the first link that appears in the list is automatically added. You then have to update the community link to get the rest.

To reproduce add the series One Piece, it will add the first approved TvDB link when there's actually 14 approved TvDB links.

**Comment by hidden4003** [comment]
I can't reproduce this, links are added although it takes an awfully long time 2-3 minutes per link (test db is sqlite, 1 series One Piece) so linking process takes more than 30 minutes to finish.

Problem is TvDB helper in the server not having a batch mode, and as each update triggers an episode update from tvdb and anime stats update which slows down things. 

Although even implementing batch mode will still leave us with waiting times in minutes range. @maxpiva is there anything that can be done with `AniDB_Anime.UpdateStatsByAnimeID(animeID);` maybe I can create a new command for that?

**Comment by hidden4003** [comment]
@ElementalCrisis this probably needs to be renamed and moved to server as it is not a client issue, it is just that after implementing cache certain api commands now take a lot more time to complete.

**Comment by ElementalCrisis** [comment]
@hidden4003 go ahead and recreate on server, I'll close this issue.
