### ISSUE TITLE
Newly Created Group Filters Shows Up Twice In Menu

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmclient#419]
![jmmdesktop_2016-07-20_01-21-07](https://cloud.githubusercontent.com/assets/9443295/16979934/a7884e2e-4e18-11e6-89f8-db43e03678fd.png)

As you can see the group filter I made labeled New Filter1 shows up twice in my group filter list. Only by restarting JMM Server does it disappear.

**Comment by hidden4003** [comment]
I've commented out the line that caused the duplicate, it was because change tracker was handling this situation, I am however unsure if the other code is needed, maybe we can remove that if statement altogether ?
