### ISSUE TITLE
Watched States Are Not Being Updated

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmclient#429]
I tried all three players and only had partial success with MPC. 

Enable Streaming is unchecked (Local Playback)
MPC - Single File - Failed
MPC - Playlist (3 Files) - Success
PotPlayer - Single File - Failed
PotPlayer - Playlist (3 Files) - Failed
VLC - Single File - Failed
VLC - Playlist (3 Files) - Failed

Enable Streaming is checked (Local Playback)
MPC - Single File - Failed
MPC - Playlist (3 Files) - Failed
PotPlayer - Single File - Failed
PotPlayer - Playlist (3 Files) - Failed
VLC - Single File - Failed
VLC - Playlist (3 Files) - Failed

@maxpiva when you get a moment can you look into this? Could use your expert touch.

**Comment by da3dsoul** [comment]
It seems it only sometimes works for me on Kodi

**Comment by ElementalCrisis** [comment]
As discussed on Discord here's what we'll be doing. 

- MPV will be integrated into JMM will full support.
- MPC will only be supported via its Web UI. 
- VLC will be supported with a JMM plugin. 
- Support for Pot Player will be dropped.

If someone would like too, they can add support for Pot Player but we will not be maintaining it as we're moving away from the current "hack" job we do and to a more long term solution.
