### ISSUE TITLE
TvDB settings are ignored

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/jmmclient#431]
client version 3.5.0.2
Default in JMM Desktop the Settings > Community Sites > The TvDB have auto download uncheck, but JMM still download those images.

I was thinking that server configuration enforce this but server have 👍 
```
    <add key="TvDB_AutoFanart" value="False" />
    <add key="TvDB_AutoFanartAmount" value="10" />
    <add key="TvDB_AutoWideBanners" value="False" />
    <add key="TvDB_AutoPosters" value="False" />
```

So this is totaly ignored then - maybe default is different that the gui shows?

**Comment by ElementalCrisis** [comment]
That's weird, 3.5.0.2 has the image downloading bug, it can't download TvDB.

**Comment by bigretromike** [comment]
Funny, as im using 3.5.0.2 fresh install and fresh database to reimport collection to make backup and ended up with tvdb downloading images :-) maybe the bug was reverse checkbox status ? When 'not' it download and when 'checked' it didnt ?

On July 31, 2016 7:51:40 AM GMT+02:00, ElementalCrisis <notifications@github.com> wrote:
>That's weird, 3.5.0.2 has the image downloading bug, it can't download
>TvDB. 
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/japanesemediamanager/jmmclient/issues/431#issuecomment-236412536

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ElementalCrisis** [comment]
What images are downloaded? Also was your images folder cleared?

**Comment by bigretromike** [comment]
Image folder was clean as it was clean install, images from tvdb fanarts, posters and third ones

On July 31, 2016 9:51:02 AM GMT+02:00, ElementalCrisis <notifications@github.com> wrote:
>What images are downloaded? Also was your images folder cleared? 
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/japanesemediamanager/jmmclient/issues/431#issuecomment-236416644

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ElementalCrisis** [comment]
One in a million I guess. I've tried now on 2 fresh DB with fresh installs and can't reproduce.
