### ISSUE TITLE
Animebyt.es torrent support no longer works

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmclient#44]
**Reported by werndlymob, Feb 3, 2013**

Animebyt.es torrent support no longer works

**Comment by CatmanIX** [comment]
Is this still true? I haven't tried it since i don't download torrents through JMM at the moment, but i would expect there to be more comments here if this was an issue people actually had problems with?

**Comment by AreFinstad** [comment]
well if it was a huge issue we would prob have heard more about it.
i think most people have moved on from sites like that TBH.
shanaproject is where its at ATM IMO.
closed sites are only good for older stuff, and most people use bakabt.me if they want something old..... most of the time.

**Comment by CatmanIX** [comment]
I use animebytes, i just don't use JMM's torrent functionality 'cause it only works with uTorrent.

They're experimenting with airing anime now as well, and they aren't old at all. Granted, I still use shana for airing anime as well.

**Comment by ElementalCrisis** [comment]
Can anyone confirm if this is still an issue?

**Comment by CtrlAltDefeat94** [comment]
It still does not work for me

@ElementalCrisis I could throw you an invite if you are not on AB yourself?

**Comment by ElementalCrisis** [comment]
It's been fixed, by Baine. 
http://jmediamanager.org/changelog/#3-5-0-1

That would be awesome, send me a message on Discord.
