### ISSUE TITLE
NullPointer on Click RenameAllGroups

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/jmmclient#440]
I think clientBinaryHTTP is null, but it is not logging an error, so I'm having issues figuring it out

**Comment by da3dsoul** [comment]
Apparently my fault a while back. Rider showed me the error, VS did not. Just pointing out that a beta ide shouldn't be beating out a business grade one produced by the largest software firm in the world...

**Comment by maxpiva** [comment]
Rider Includes Resharper, install resharper 😄
