### ISSUE TITLE
Series selection for renaming preview not working

### ISSUE THREAD

**Issue by pmcthor777** [japanesemediamanager/jmmclient#441]
The series selection for renaming preview is not working correctly. After searching for a series and clicking on the 'Use This' button, an error is returned:

Value cannot be null.
Parameter name: source

It seems like the series name isn't being passed to the query after selecting it. This is on the latest version 3.6.0.2

**Comment by ElementalCrisis** [comment]
Can you post your logs?

I was able to rename both the series and group with no problems.

**Comment by pmcthor777** [comment]
Here's my log

[2016-09-02.txt](https://github.com/japanesemediamanager/jmmclient/files/452898/2016-09-02.txt)

**Comment by SL-Gundam** [comment]
I've got the same error. This only happens for a single series selection

**Comment by SL-Gundam** [comment]
Fix works
Thank you

**Comment by da3dsoul** [comment]
Yep

**Comment by pmcthor777** [comment]
Can you tell me how I can fix it myself?

**Comment by SL-Gundam** [comment]
The milestone is incorrect
It's fixed in 3.6.0.3 which you can download from the JMM website
