### ISSUE TITLE
JMMClient 3.6.0.2 crashes on open

### ISSUE THREAD

**Issue by nettosama** [japanesemediamanager/jmmclient#444]
After upgrading Server and Client to 3.6.0.2, It all worked fine, but Client now crashes on open.

I've attached the log:

[2016-09-03.txt](https://github.com/japanesemediamanager/jmmclient/files/453155/2016-09-03.txt)

**Comment by da3dsoul** [comment]
@ElementalCrisis it is an installer build error. Win32 Primitives was not included. ![screenie](http://pasteboard.co/1DiprRjE2.png)

**Comment by da3dsoul** [comment]
@nettosama try running as admin

**Comment by ElementalCrisis** [comment]
Double-checked and that file is included in the install. @nettosama can you delete everything except your config file in the install directory and reinstall? Also can you check to make sure that DLL file is there after you reinstall?

**Comment by nettosama** [comment]
The file is there but it crashes anyways, I think I replicated the issue on another PC, it crashes after enabling WebUI integration for MPC-HC. If I edit the config file and set it to False, it opens correctly again.

**Comment by ElementalCrisis** [comment]
Ah OK, disable Web UI for now as it's getting redone in 3.6.5.

**Comment by ElementalCrisis** [comment]
Forgot we already had this issue reported, https://github.com/japanesemediamanager/jmmclient/issues/430.

Closed as fixed in 3.6.5
