### ISSUE TITLE
JMM Client 3.6.0.3 fails to open

### ISSUE THREAD

**Issue by calystegia** [japanesemediamanager/jmmclient#447]
Appears in task manager, window does not appear.  Possibly config related as deleting the config file allows for re-opening.

[2016-09-03.txt](https://github.com/japanesemediamanager/jmmclient/files/453456/2016-09-03.txt)

Edit: Problem is caused by being able to select a default player when it isn't being detected.  
Click an option>Dropdown menu is not closed>Line is written into config>Client won't re-open.

**Comment by calystegia** [comment]
Seems like this line in the config is causing issues
    <add key="DefaultPlayer_GroupList" value="0" />
Deleting it allows it to re-open.

**Comment by ElementalCrisis** [comment]
Couple idea, we can only have the drop-down list populate with detected players and add a fallback that uses Windows Default if previously selected player is no longer available.

**Comment by hidden4003** [comment]
Problem is caused by a bad PATH environment variable, I will add the check so we log the error and not completely crash.
