### ISSUE TITLE
Automatically mark Files as watched is not working correctly

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmclient#45]
**Reported by kavugg, Feb 8, 2013**

*What steps will reproduce the problem?*
1. Set the percentage to any value. (I tested this with 75%, 90% and 95%)
2. Play a file that has not yet been opened with MPC and therefore has no entry in the .ini-file.

*What is the expected output? What do you see instead?*
The file is then immediatly marked as watched even though it shouldn't. Most likely upon receiving an entry in the .ini-file.

*What version of the product are you using? On what operating system?*
I am using JMM Desktop version 3.1.28.0 and MPC-HC lite version 1.6.6.6659.

*Please provide any additional information below.*
If you unmark this file and the entry in the .ini is still there, rewatching the episode "fixes" the problem because the mark-percentage is working correctly then.

**Feb 13, 2013 kavugg**

As I can't edit my comment above, here is a small update regarding this issue:

After looking at the code, I found out that a file is marked as watched if
a) File-Pos in the .ini = 0
b) File-Pos is above the percentage.

These obviously aren't any news to you, but according to this I did a little experiment:
1. Start a file and close MPC as fast a possible.
2. Look at the .ini and observe the corresponding file-position.

As I closed the window right before the episode would start (and therefore the MPC-logo was still visible), the file-position of that file was 0.
According to this I'm guessing that your filewatcher is "too fast" and therefore reads the 0 and marks the file as watched.

I hope this helps you in fixing this.

**Comment by Daemeron** [comment]
I did a little bit of research on that part and case does not seems as simple as @kavugg describes.

I believe someone made wrong assumption that Position = 0 in *.ini file means that someone played the whole file. It just means that file was either stopped or just started.

Please note that mpc does not trigger *.ini file update at all times or at least periodically. It seems as *.ini file solution for tracking playback is rather limited. It may be sufficient though in most cases.

Manual change of file position via clicks modify the file as well as starting playback and switching file. Using arrows to navigate forward and backwards however as well regular playback do not that.

I did a little fix for that and I am going to commit that and make merge request.

**Comment by ElementalCrisis** [comment]
Fixed in #302.
