### ISSUE TITLE
JMM desktop series filter with tags since version 3.6.x.x

### ISSUE THREAD

**Issue by claudiogenta** [japanesemediamanager/jmmclient#456]
After migration to version 3.6 of JMM server+desktop, series filtering based on Custom Tags is not working anymore.
e.g. I have a custom Tag "processed" and a filter group "Unprocessed" contatining all series with do not have "processed" custom tag. The series correctly have still the custom Tags after migration, but the "Unprocessed" group contains all my series, regardless of having or not the tag.
Also while modifiying existing group filter, it is possible to add conditions, but not to remove them.

Thanks

**Comment by ElementalCrisis** [comment]
> After migration to version 3.6 of JMM server+desktop, series filtering based on Custom Tags is not working anymore.

Known bug in 3.6 (https://github.com/japanesemediamanager/jmmclient/issues/433), we're looking to have it fixed in 3.6.5.

>  Also while modifiying existing group filter, it is possible to add conditions, but not to remove them.

Hmm, I'm able to reproduce this but it's sporadic, sometimes it will remove the filter condition while other times it won't.

**Comment by maxpiva** [comment]
This is fixed on master, custom tags works as expected.
