### ISSUE TITLE
Video player MPC-HC is not detected

### ISSUE THREAD

**Issue by d3xMachina** [japanesemediamanager/jmmclient#459]
On JMM Desktop 3.6.1.0, MPC-HC is not detected. In "Settings/Video Player" it shows "Not installed" for Media Player Classic even if the "Test MPC INI File" works with the folder I specified. I'm using the mpc-hc 1.7.10.252 (installed with the installer version) and Windows 10 x64 with the anniversary update. On my other computer with the 3.5.0.2 version I don't have this issue.

**Comment by da3dsoul** [comment]
Set mp-hc as the default player for at least one file type. It is a known issue

**Comment by d3xMachina** [comment]
My mpc-hc is already set as the default player for all the video formats in Windows :/

**Comment by da3dsoul** [comment]
Then choose Windows default from the drop down

**Comment by d3xMachina** [comment]
I already tried that.

**Comment by da3dsoul** [comment]
Fair enough @ElementalCrisis up to bat

**Comment by ElementalCrisis** [comment]
Hmm, uninstalled all video players and checked to make sure JMM Desktop said Not Installed for 
Running JMM 3.6.1.0

MPC-HC. Then installed MPC-HC 1.7.10.252x64, right-clicked on an .MKV file and made MPC-HC the default player then loaded JMM Desktop and it detected MPC-HC.

Uninstalled MPC-HC 1.7.10.252x64 and checked to make sure JMM Desktop said Not Installed for MPC-HC. Installed MPC-HC 1.7.10.252x86, right-clicked on an .MKV file and made MPC-HC the default player then loaded JMM Desktop and it detected MPC-HC.

So I can confirm it works with the standalone MPC-HC install which means its an error on your end, can you double-check and make sure you have the following registry keys?

`HKEY_CURRENT_USER\SOFTWARE\MPC-HC\MPC-HC`

**Comment by d3xMachina** [comment]
I don't have the following key after installing mpc-hc, I tried both x86 and x64 and also the one featured on mpc-hc website. I even launched the installer with admin rights... I manually created the key and now it works. JMM crash (it doesn't respond) though when I try to use "MPC Web UI Port" but maybe I should create a new ticket for that.

**Comment by ElementalCrisis** [comment]
The key is not created during install but only when you make MPC-HC the default player for at least one filetype. 

Don't worry about the MPC ini or Web UI settings, INI has been removed in 3.6.5 and Web UI has been reworked.

**Comment by d3xMachina** [comment]
On Windows 10, when you click on "Set as default program" in mpc-hc, it shows a popup saying that you need to change the default application for movies yourself in the windows settings and it didn't create any key in the registry for me. Also, thanks for your help.

**Comment by da3dsoul** [comment]
What if you choose open with and always use this

**Comment by d3xMachina** [comment]
Same.

**Comment by misakitchi** [comment]
Thanks!
I had this bug too and searched for a week... :(

The important part is in Registry (regedit):
[HKEY_CURRENT_USER\Software\MPC-HC\MPC-HC]
"ExePath"="C:\\Program Files (x86)\\MPC-HC\\mpc-hc.exe"

How i have resolved it:
Uninstall MPC-HC and choose option "delete settings"
Reinstall MPC-HC
Open MPC-HC go in options and verify if "store settings in .ini" is disable!
Close MPC-HC
Now in Explorer right-click a video file (*.mkv) then "Open With" and chose MPC-HC by default
And now its working again in JMM Desktop! :)

You can verify: open regedit and find the key
[HKEY_CURRENT_USER\Software\MPC-HC\MPC-HC]
It must be:
"ExePath"="C:\\Program Files (x86)\\MPC-HC\\mpc-hc.exe"

**Comment by misakitchi** [comment]
Oh and can you let this post open but change name:
[Tutorial/Bug] MPC-HC: Video player is not detected / File not found
Thanks! :)
