### ISSUE TITLE
Grave accent ( ` ) vs apostrophe ( ' )

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmclient#46]
**Reported by IvanAhn, Mar 14, 2013**

I don't see a way to escape the apostrophe. The reason I was looking for this was because AniDB uses ` instead of ' and that's always bugged me. So I wanted to do something like:

```
DO REPLACE '`' '\'' // assuming \ escapes the '
```

**Comment by deusxanime** [comment]
Came to post this exact issue. Renaming pulls from AniDB which seems to like backtick `, but I prefer to use standard apostrophe ' when I name files. Running into the same thing where it doesn't work in my import rename script on JMM Desktop (trying same syntax you have there). Of course that means I have to run import with renaming, manually change to the ' character, and then import again without renaming to get it to work correctly.

Hopefully they can get it figured out - some way to allow an escape character like you suggest or some other way. Subscribing for updates on this, though it has already been 4 months it appears without much traction.

**Comment by ElementalCrisis** [comment]
Fixed, will be available in the next version of JMM.

**Comment by deusxanime** [comment]
Awesome! What will be the syntax to use it in renaming scripts?

**Comment by ElementalCrisis** [comment]
Hmm, Baine's fix is more for when searching in JMM Desktop and linking with community sites. I"ll talk to him about adding support in the renaming utility.

**Comment by deusxanime** [comment]
That'd be great. I think that is what IvanAhn and I were more looking for with this issue.

**Comment by Baine** [comment]
should be fixed in 0beb73d80b3e739a379e673b675a4d68e6fb1c78

**Comment by deusxanime** [comment]
So how will it work in the renaming scripting then? Will JMM automatically use ' instead of ` after this update, or will we need to do some kind of DO REPLACE as part of the script?

**Comment by Baine** [comment]
atm it will replace any occurence of ` in the final filename with '
no DO REPLACE needed.
leaves open a potential conflict for when a user actually would want that inside the name (yes, i am aware of that case, maybe there'll be an option or something sometime in the future)
