### ISSUE TITLE
Error making Filter

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/jmmclient#460]
I'm getting nothing when trying to make a filter.
The Filter has Finished Airing and Video Quality (TV)
The filter both previews and evaluates as empty.

**Comment by da3dsoul** [comment]
Okay, I can verify this only happens with Video Quality

**Comment by da3dsoul** [comment]
Nvm that error is completely unrelated. The filter doesn't work though.

**Comment by ElementalCrisis** [comment]
Leftover bug from Cache addon.

https://github.com/japanesemediamanager/jmmclient/issues/433
