### ISSUE TITLE
Unable To Set User Password

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmclient#461]
Inputting a password for a user account does nothing, no matter what you input you can still login with a blank password field.

**Comment by RickDB** [comment]
Tested with latest master branch and looks fixed, did the following test:

- Created new user: "Test"
- Afterwards went to user and clicked on "Change password" and set password: 1234
- Clicked on change user icon (bottom right) and inputted blank and incorrect password for user "Test", will show invalid password in both cases.
- Filled in correct password and works

**Comment by RickDB** [comment]
Seems we have a test case where it would fail, if you change password and afterwards click on save user it will clear the password, fix for this in place and will push to 3.7 later.
