### ISSUE TITLE
Trakt PIN / token not saved

### ISSUE THREAD

**Issue by RickDB** [japanesemediamanager/jmmclient#464]
**Issue**

When adding the pin via "Settings - Community sites - > Trakt" it will show that the it's applied (with expiry date) however when restarting JMMClient it will no longer show a PIN filled or expiry date so looks like it isn't saving this setting.
Checked to make sure others like MAL are saved in case of general settings issue but those work.

**To reproduce**

Press get PIN from "Settings - Community sites - > Trakt" and fill it in afterwards, click authorize and you will see an "Current token is valid until: x date".
Now restart JMMClient and you will notice the Trakt PIN is no longer filled and expiry date is blank

**Comment by da3dsoul** [comment]
This was annoying and why I didn't really use trakt

**Comment by da3dsoul** [comment]
I just noticed netsplite isn't added as a member yet. :wink:

**Comment by RickDB** [comment]
Fix found as it was related to visibility on first start which thanks to @ElementalCrisis was tracked easily :)
