### ISSUE TITLE
Logical error that wipe out image collection

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/jmmclient#479]
When server and client use same image path and in client you go to:
Settings > Community Site > Update Local Images 
The image collection is wipe out (from both server and client as they share path)
and Client ask Server to send new one...
As the server have not images because it share image folder there is a error while sending it.

This is error in current master.

**Comment by da3dsoul** [comment]
That's not a bug, it has a very obvious note

**Comment by bigretromike** [comment]
You know it work in different way for different paths ?
for same path it wipe out collection without redownloading it
for different paths it remove local collection and redownload it from server

If it by design then it should work one way or another...

**Comment by bigretromike** [comment]
Yes, you have right.. there is note which i missed - but why no one add anything to it ?
I will add something then...

**Comment by RickDB** [comment]
Improved this behaviour in commit id a4c74f0e66f7475f9b29146947f8c886fffb76b1

It now hides the button and hint text in case image path equals server path, even with the hint text like before there's a change people don't read and kill their server image storage and this prevents that :)
