### ISSUE TITLE
Add qBittorrent as alternative to uTorrent

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmclient#53]
**Reported by marcojakko86, Jun 4, 2013**

I don't know how many people use qbittorrent instead of uTorrent, i find it faster and ligher. Guys at http://www.transdroid.org/ use this java class to make the remote calls to qbittorrent. 

https://code.google.com/p/transdroid/source/browse/lib/src/org/transdroid/daemon/Qbittorrent/QbittorrentAdapter.java

**Comment by bigretromike** [comment]
There is still a realy "support all torrents" solution made by me: https://github.com/japanesemediamanager/jmmclient/pull/270 

BlackHole is the folder you set to download .torrent file and every current torrent client can easly scan for those files in chosen folder. win-win

**Comment by ElementalCrisis** [comment]
Similar to #10, going to close all torrent program support issues and make #10 the main issue for it.
