### ISSUE TITLE
JMM Desktop: Hide tags when unwatched or just hide them altogether through collapsing

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmclient#56]
**Reported by windfury000@yahoo.com, Jun 19, 2013**

It's quite difficult to manage stuff while trying to avoid reading those tags. Sadly, I've gotten plenty of spoilers just because I get a quick glance of them. :(

I tried collapsing, but it still shows the top voted tags (which usually contains a fair amount of the biggest spoilers).

So, an option like those in the Display tab for settings would be nice (Like Hide Episode Image and Overview When Unwatched) or just completely hide them when collapsed.

**Comment by ElementalCrisis** [comment]
Here's my purposed fix. 
![jmmd - tags changes](https://cloud.githubusercontent.com/assets/9443295/9750270/4bb84804-564a-11e5-85cb-ad52950ee3d7.png)

Creating an option to hide tags would remove any usefulness they have for that series. Instead I removed the 5 tags that are displayed and changed the wording to include a message about possible spoilers.
