### ISSUE TITLE
Can't delete in Ignored menu in JMM Desktop

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmclient#61]
**Reported by Are.Finstad, Aug 27, 2013**

*What steps will reproduce the problem?*
1.press delete on the ignored menu in utilities.

*What is the expected output? What do you see instead?*
i expect it to delete the files marked (one or more)
what i see? nothing, nothing is happening. not in the folder or in the JMM Desktop menu.

*Please provide any additional information below.*
backup of all my Logs up to this post. hope you find something. 
http://sdrv.ms/15CGuuI

**Comment by ElementalCrisis** [comment]
Fixed, will be available in the next version of JMM.
