### ISSUE TITLE
View series that have files in more than one location

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/jmmclient#67]
**Reported by Are.Finstad, Sep 25, 2013**

be able to view series that have files in more than one location.
files get moved all the time, and sometimes a drive is full and you need to start on another one. series get split up across drives and folders.

wouldn't it be nice to have a way for the JMM server to tell you witch series and witch files this is happening too? JMM already knows where all the files are. all it need to do is to cross reference between the folder locations.

i think this would be a great addition to the system for neatness sake :D

**Comment by ElementalCrisis** [comment]
Added in Version 3.4.6.2
