### ISSUE TITLE
Hasher should run seperate instances for different drives

### ISSUE THREAD

**Issue by themountain632** [japanesemediamanager/jmmclient#79]
It would be nice if the hasher.dll ran multiple instances (for files on other drives) instead of doing things sequentially regardless of where the files are located.

**Comment by ElementalCrisis** [comment]
More of a JMM Server feature request.

**Comment by AreFinstad** [comment]
copy this over to JMMS maybe? its a nice thing to have for sure. i would love it and use it right away.

**Comment by ElementalCrisis** [comment]
Combined with https://github.com/japanesemediamanager/jmmserver/issues/207.
