### ISSUE TITLE
support thetvdb Seasons in renaming rules. 

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/jmmclient#85]
[enhancement] support thetvdb Seasons in renaming rules. 

there is no support for season renaming (you already support linking episodes to tvdb so they should know witch season they are contained with)

you should be able to let the renamer script rename after seasons and episodes like all other media servers. "[Animename] - SXXEXX - [Episode Title] [Version number][release group][CRC] (for example (ofc you can make it to whatever like always with the script, but thats how i would have done it IMO))

by using such a naming method makes the other media servers aware of what kind of file it is (it will not know if its a series or a movie (MediaBrowser & Plex))

EDIT: if you want to read up on how Plex handles this then you can read here: https://support.plex.tv/hc/en-us/categories/200028098-Media-Preparation 
or here: https://oldwiki.plexapp.com/index.php?title=Media_Naming_and_Organization_Guide
they really cover all the bases here.

also a thing Plex does that you can do with the App, Theme Songs for series. Plex Support Theme Songs on Series if you browse a series .

**Comment by anzerman** [comment]
:+1:
