### ISSUE TITLE
[issue] retries connection too soon after ban creating a loop

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/jmmclient#89]
[issue] retries connection too soon after ban creating a loop.
i can hit a ban from time to time when i try to update all AniDB data.
once i have a ban the program will try to connect from time to time to check if the ban is lifted, tho it does so too soon every time and causing an endless loop unless i close the JMM server for a day or two (depends on length of ban, and as it gets longer because of the retries its hard to know when its going out)

we should  be able to set a timer button for when it will retry (12,24,48,72h?)
that way we can still use the server and its clients without needing to close the hole server.
pausing the processes does not help as it will still retry when it wants too.

**Comment by ElementalCrisis** [comment]
With the change in how JMM access AniDB, this won't be an issue any longer.

https://github.com/japanesemediamanager/jmmserver/issues/379
