### ISSUE TITLE
Episode Summaries And Image Off By One

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/jmmclient#95]
Hello,

I've noticed with a couple series that when I link them to their TheTvDB counterparts, the episode summaries and pictures are offset by one.  

http://thetvdb.com/?tab=season&seriesid=80000&seasonid=27367&lid=7

![jmm - episode problem](https://cloud.githubusercontent.com/assets/9443295/4857108/813ebbc4-60c9-11e4-88ea-8d0d808cc648.png)

**Comment by ElementalCrisis** [comment]
Closing this as its not an issue with JMM.

**Comment by jmediamanager** [comment]
Yeah I have uploaded hundreds of images over the years, especially for episodes.

I requested they change their API to allow submission of images that way, but never got a response

**Comment by AreFinstad** [comment]
well to be fair, they like to lock everything and makes us ask them to open them for us when we needs to edit stuff......really now. sad really.
they should just keep track of what is changed and the rollback changes that is bad (ofc someone as to actually check those tho)

**Comment by ElementalCrisis** [comment]
I understand the logic behind the decision, people can be malicious. I just wish there was a more automated system for approving/denying and submiting deletion requests.

**Comment by AreFinstad** [comment]
i can see why they do it, but there is many sites that is does handle this in a much smoother way for the editors without mod rights.

but i really feel the Anime side of tvdb is actually pretty bad (atleast the thumbs) as the thumbs are infected with subs, icons and many other things that isnt good....... and dont forget the spoiler thumbs.
